Repository projectcontour/contour, pull requests merged in 2020-04, with the labels that each got.

#2386 Add Ingress status management
  cmd/contour/ingressstatus.go
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  examples/contour/02-rbac.yaml
  examples/contour/03-envoy.yaml
  examples/render/contour.yaml
  internal/contour/handler.go
  internal/k8s/ingressstatus.go
  internal/k8s/ingressstatus_test.go
Labels: release note

#2381 internal/contour: enforce SNI name bindings
  internal/contour/listener.go
  internal/contour/listener_test.go
  internal/contour/route.go
  internal/contour/route_test.go
  internal/e2e/lds_test.go
  internal/e2e/rds_test.go
  internal/envoy/listener.go
  internal/featuretests/externalname_test.go
  internal/featuretests/featuretests.go
  internal/featuretests/headercondition_test.go
  internal/featuretests/headerpolicy_test.go
  internal/featuretests/ingressclass_test.go
  internal/featuretests/loadbalancerpolicy_test.go
  internal/featuretests/mirrorpolicy_test.go
  internal/featuretests/replaceprefix_test.go
  internal/featuretests/retrypolicy_test.go
  internal/featuretests/rootnamespaces_test.go
  internal/featuretests/tcpproxy_test.go
  internal/featuretests/timeoutpolicy_test.go
  internal/featuretests/tlscertificatedelegation_test.go
  internal/featuretests/tlsprotocolversion_test.go
  internal/featuretests/websockets_test.go
  site/docs/master/httpproxy.md
Labels: release note

#2406 internal/envoy: enable merge_slashes on the httpconnection manager for all listeners
  internal/envoy/listener.go
  internal/envoy/listener_test.go
Labels: release note

#2390 site: documentation for TLS client authentication
  site/docs/master/httpproxy.md
Labels: documentation

#2400 build: apply standard Docker image labels
  Makefile
Labels: release note

#2416 Add ingress class filtering to ingress status updating
  internal/annotation/annotations.go
  internal/annotation/annotations_test.go
  internal/annotation/timeout.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  internal/k8s/ingressstatus.go
  internal/k8s/objectmeta.go
Labels: release note

#2420 site: Update annotations doc with better ingress.class information
  site/docs/master/annotations.md
Labels: release note

#2399 internal/build: Add contour version as a CLI option
  Makefile
  cmd/contour/contour.go
  internal/build/version.go
Labels: release note

#2407 internal/health: separate health and metrics services
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  design/listener-design.md
  internal/health/health.go
  internal/metrics/metrics.go
  site/_guides/health-checking.md
  site/_guides/prometheus.md
Labels: area/metrics, release note

#2440 site: add code highlighting
  site/_config.yml
  site/_scss/_styles.scss
  site/_scss/site/utilities/_highlighter.css
  site/docs/master/httpproxy.md
Labels: website

#2445 doc: document the Contour configuration file
  site/_data/master-toc.yml
  site/_guides/structured-logs.md
  site/docs/master/configuration.md
Labels: documentation

#2458 Add docs search to the site
  site/_layouts/docs.html
  site/_scss/_styles.scss
  site/_scss/site/layouts/_docsearch.scss
Labels: website

#2448 upgrade client-go to v0.18.2
  examples/contour/01-crds.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  internal/certgen/certgen.go
  internal/k8s/ingressstatus.go
  internal/k8s/status.go
Labels: release note
