Repository projectcontour/contour, pull requests merged in 2020-11, with the labels that each got.

#3097 site: Fix typo in HTTPProxy reference
  site/docs/main/config/tls-termination.md
  site/docs/v1.4.0/httpproxy.md
  site/docs/v1.5.0/httpproxy.md
  site/docs/v1.5.1/httpproxy.md
  site/docs/v1.6.0/httpproxy.md
  site/docs/v1.6.1/httpproxy.md
  site/docs/v1.7.0/httpproxy.md
  site/docs/v1.8.0/httpproxy.md
  site/docs/v1.8.1/httpproxy.md
  site/docs/v1.8.2/httpproxy.md
  site/docs/v1.9.0/httpproxy.md
Labels: area/documentation

#3137 Increase the max width of the container to 1340px
  site/_scss/site/settings/_variables.scss
Labels: area/website

#3155 Remove legacy annotation support
  internal/annotation/annotations.go
  internal/annotation/annotations_test.go
  internal/dag/builder_test.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/dag/ingress_processor.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  internal/featuretests/v3/backendcavalidation_test.go
  internal/featuretests/v3/ingressclass_test.go
  internal/featuretests/v3/retrypolicy_test.go
  internal/featuretests/v3/route_test.go
  internal/featuretests/v3/timeoutpolicy_test.go
  internal/featuretests/v3/tlsprotocolversion_test.go
  internal/featuretests/v3/upstreamprotocol_test.go
  internal/featuretests/v3/websockets_test.go
  internal/xdscache/v3/cluster_test.go
  internal/xdscache/v3/listener_test.go
  internal/xdscache/v3/route_test.go
Labels: release-note

#3151 chore: update Envoy to v1.16.1
  Makefile
  examples/contour/03-envoy.yaml
  examples/render/contour.yaml
  site/_resources/envoy.md
Labels: release-note
