Repository projectcontour/contour, pull requests merged in 2020-07, with the labels that each got.

#2632 add configurable idle timeout
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/contour/listener.go
  internal/contour/listener_test.go
  internal/envoy/listener.go
  internal/envoy/listener_test.go
  site/docs/master/configuration.md
Labels: release-note

#2661 cmd/contour: add config file option to set stream idle timeout
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/contour/listener.go
  internal/contour/listener_test.go
  internal/envoy/listener.go
  internal/envoy/listener_test.go
  site/docs/master/configuration.md
Labels: release-note

#2670 cmd/contour: add config file option to set max connection duration
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/contour/listener.go
  internal/contour/listener_test.go
  internal/envoy/listener.go
  internal/envoy/listener_test.go
  site/docs/master/configuration.md
Labels: release-note

#2646 Add support for retry on, retriable status codes
  .golangci.yml
  Makefile
  _integration/testsuite/httpproxy/011-retry-policy-validation.yaml
  apis/contour/v1beta1/zz_generated.deepcopy.go
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  examples/contour/01-crds.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  internal/envoy/route.go
  internal/envoy/route_test.go
  site/docs/master/api-reference.html
Labels: area/httpproxy, kind/api-change, release-note

#2675 cmd/contour: add config file option to set drain timeout
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/contour/listener.go
  internal/contour/listener_test.go
  internal/envoy/listener.go
  internal/envoy/listener_test.go
  site/docs/master/configuration.md
Labels: release-note

#2682 examples/contour: upgrade to Envoy v1.15.0
  examples/contour/03-envoy.yaml
  examples/render/contour.yaml
Labels: release-note

#2642 Add design for HTTPProxy conditions
  design/httpproxy-status-conditions.md
Labels: kind/design

#2694 Add CII Badge
  README.md
Labels: area/documentation

#2638 Enable TCP keepalive on listener sockets.
  internal/contour/listener_test.go
  internal/contour/visitor_test.go
  internal/e2e/lds_test.go
  internal/envoy/listener.go
  internal/envoy/listener_test.go
  internal/envoy/stats.go
  internal/envoy/stats_test.go
  internal/envoy/tcp_keepalive.go
  internal/featuretests/backendcavalidation_test.go
  internal/featuretests/downstreamvalidation_test.go
  internal/featuretests/fallbackcert_test.go
  internal/featuretests/rootnamespaces_test.go
  internal/featuretests/tcpproxy_test.go
  internal/featuretests/tlscertificatedelegation_test.go
  internal/featuretests/tlsprotocolversion_test.go
Labels: release-note

#2708 site: clarify cert-manager guide
  site/_guides/cert-manager.md
Labels: area/website

#2643 design: add initial external authorization proposal
  design/external-authorization-design.md
Labels: kind/design

#2706 Add conditions to HTTPProxy and TLSCertificateDelegation
  apis/projectcontour/v1/detailedconditions.go
  apis/projectcontour/v1/doc.go
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/kubeconditions.go
  apis/projectcontour/v1/tlscertificatedelegation.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  examples/contour/01-crds.yaml
  examples/render/contour.yaml
  site/docs/master/api-reference.html
Labels: release-note

#2726 cmd/contour: add TimeoutConfig.RequestTimeout
  cmd/contour/serve.go
  cmd/contour/serve_test.go
  cmd/contour/servecontext.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/contour/listener.go
  internal/envoy/listener.go
  internal/envoy/listener_test.go
  internal/featuretests/envoy.go
  site/docs/master/configuration.md
Labels: release-note, release-note-action-required

#2746 internal/envoy: add common API for ClusterLoadAssignment names
  go.mod
  internal/contour/endpointstranslator.go
  internal/envoy/cluster.go
  internal/envoy/cluster_test.go
  internal/featuretests/externalname_test.go
Labels: kind/cleanup
