Repository projectcontour/contour, pull requests merged in 2020-08, with the labels that each got.

#2751 cmd/contour: refactor shutdown-manager to initiate shutdown using an Exec command
  cmd/contour/contour.go
  cmd/contour/shutdownmanager.go
  examples/contour/03-envoy.yaml
  examples/render/contour.yaml
Labels: release-note

#2745 internal/contour: simplify the endpoints translator
  internal/contour/endpointstranslator.go
  internal/contour/endpointstranslator_test.go
Labels: kind/cleanup

#2787 internal/assert: Better protobuf diffs by aliasing testify/assert
  .golangci.yml
  cmd/contour/serve_test.go
  cmd/contour/servecontext_test.go
  cmd/contour/shutdownmanager_test.go
  go.mod
  go.sum
  internal/assert/assert.go
  internal/contour/cluster_test.go
  internal/contour/listener_test.go
  internal/contour/route_test.go
  internal/contour/secret_test.go
  internal/dag/policy_test.go
  internal/dag/secret_test.go
  internal/envoy/accesslog_test.go
  internal/envoy/bootstrap_test.go
  internal/envoy/healthcheck_test.go
  internal/envoy/stats_test.go
  internal/featuretests/featuretests.go
  internal/timeout/timeout_test.go
Labels: area/testing

#2812 site: add `area/operational` label
  site/_data/github-labels.yaml
Labels: area/tooling, area/website

#2830 Add deprecation warning log for contour.heptio.com annotations
  internal/dag/cache.go
Labels: release-note
