Repository projectcontour/contour, pull requests merged in 2020-06, with the labels that each got.

#2587 internal/contour: remove IngressRoute code
  internal/contour/cluster_test.go
  internal/contour/handler.go
  internal/contour/listener_test.go
  internal/contour/metrics.go
  internal/contour/metrics_test.go
  internal/contour/route_test.go
  internal/contour/secret_test.go
Labels: area/ingressroute

#2588 internal/dag: simplify the cache initialization
  internal/dag/cache.go
Labels: kind/cleanup

#2590 internal/dag: Remove IngressRoute Code
  internal/dag/builder.go
  internal/dag/builder_test.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  internal/dag/status.go
  internal/dag/status_test.go
  internal/e2e/cds_test.go
  internal/e2e/lds_test.go
  internal/e2e/rds_test.go
  internal/e2e/sds_test.go
  internal/featuretests/backendcavalidation_test.go
  internal/featuretests/externalname_test.go
  internal/featuretests/ingressclass_test.go
  internal/featuretests/loadbalancerpolicy_test.go
  internal/featuretests/retrypolicy_test.go
  internal/featuretests/rootnamespaces_test.go
  internal/featuretests/tcpproxy_test.go
  internal/featuretests/timeoutpolicy_test.go
  internal/featuretests/tlscertificatedelegation_test.go
  internal/featuretests/tlsprotocolversion_test.go
  internal/featuretests/websockets_test.go
Labels: area/ingressroute

#2609 website: add skriss as maintainer
  site/_contributors/02-steve-kriss.md
  site/img/contributors/steve-kriss.png
Labels: area/website

#2611 docs: describe CONTOUR_NAMESPACE env var usage
  site/docs/master/configuration.md
Labels: area/documentation

#2612 docs: fix inclusion example
  examples/example-workload/httpproxy/04-inclusion/httpproxy-inclusion-samenamespace.yaml
  site/docs/master/httpproxy.md
Labels: area/documentation

#2622 cmd/contour: support defaulting HTTP protocol versions
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/annotation/annotations.go
  internal/contour/listener.go
  internal/contour/listener_test.go
  internal/contour/visitor_test.go
  internal/dag/builder.go
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/e2e/lds_test.go
  internal/envoy/listener.go
  internal/envoy/listener_test.go
  site/_resources/faq.md
  site/docs/master/configuration.md
Labels: release-note
