Repository projectcontour/contour, pull requests merged in 2020-10, with the labels that each got.

#3005 cmd/contour: remove deprecated request-timeout field from config file
  cmd/contour/serve.go
  cmd/contour/serve_test.go
  cmd/contour/servecontext.go
  site/docs/main/configuration.md
Labels: release-note, release-note-action-required

#3007 internal: update HTTPProxy & Ingress default min TLS version to 1.2
  cmd/contour/serve.go
  internal/annotation/annotations.go
  internal/dag/builder_test.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/featuretests/envoy.go
  internal/featuretests/listeners_test.go
  internal/xdscache/v2/listener_test.go
  site/docs/main/annotations.md
  site/docs/main/httpproxy.md
Labels: release-note, release-note-action-required

#3029 Update Envoy to v1.16.0
  Makefile
  examples/contour/03-envoy.yaml
  examples/render/contour.yaml
Labels: release-note

#3031 build multi-arch Docker image for linux/amd64 and linux/arm64
  .github/workflows/build_main.yaml
  .github/workflows/build_tag.yaml
  Dockerfile
  Makefile
  hack/actions/build-and-push-release-images.sh
Labels: release-note

#3018 xDS v3 config file option
  cmd/contour/serve.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/docs/main/configuration.md
Labels: release-note

#3049 doc: reclassify Contour configuration as deployment
  site/_data/main-toc.yml
Labels: area/documentation

#3048 doc: move Envoy listener information to the FAQ
  site/_data/main-toc.yml
  site/_resources/faq.md
  site/docs/main/troubleshooting/envoy-not-listening.md
Labels: area/documentation

#3042 Add envoy-json-logging-custom-fields-design doc
  design/envoy-json-logging-custom-fields-design.md
Labels: area/deployment, kind/design

#3073 config: Change xds-server-version to be plural and serve multiple xDS versions
  cmd/contour/serve.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/featuretests/v2/featuretests.go
  internal/xds/server.go
  internal/xds/v2/server.go
  internal/xds/v3/server.go
  internal/xdscache/v2/server_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/docs/main/configuration.md
Labels: release-note
