Repository projectcontour/contour, pull requests merged in 2020-05, with the labels that each got.

#2498 site: update labels for stale issue workflow
  .github/workflows/stale.yaml
Labels: area/tooling

#2333 bootstrap: support for Envoy xDS certificate rotation
  cmd/contour/bootstrap.go
  cmd/contour/contour.go
  internal/envoy/bootstrap.go
  internal/envoy/bootstrap_test.go
Labels: release-note

#2477 internal: implement fallback certificate
  apis/projectcontour/v1/httpproxy.go
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-contour-config.yaml
  examples/contour/01-crds.yaml
  examples/render/contour.yaml
  internal/contour/listener.go
  internal/contour/listener_test.go
  internal/contour/route.go
  internal/contour/route_test.go
  internal/contour/secret_test.go
  internal/contour/visitor_test.go
  internal/dag/builder.go
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/status_test.go
  internal/envoy/listener.go
  internal/featuretests/envoy.go
  internal/featuretests/fallbackcert_test.go
  internal/featuretests/featuretests.go
  internal/k8s/status.go
  internal/sorter/sorter.go
  internal/sorter/sorter_test.go
  site/docs/master/api-reference.html
Labels: release-note

#2553 examples/contour: switch to reloadable xDS certificates
  .travis.yml
  examples/contour/02-job-certgen.yaml
  examples/contour/03-contour.yaml
  examples/contour/03-envoy.yaml
  examples/render/contour.yaml
Labels: release-note-action-required
