Repository projectcontour/contour, pull requests merged in 2020-09, with the labels that each got.

#2848 design: backend TLS with client certificate
  design/tls-backend-client-authentication.md
Labels: area/operational, area/tls, kind/design

#2905 internal/timeout: return parse errors instead of defaulting to infinity
  cmd/contour/serve.go
  cmd/contour/serve_test.go
  internal/annotation/annotations.go
  internal/contour/route_test.go
  internal/dag/builder_test.go
  internal/dag/extension_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  internal/dag/status_test.go
  internal/featuretests/authorization_test.go
  internal/featuretests/extensionservice_test.go
  internal/featuretests/timeoutpolicy_test.go
  internal/timeout/timeout.go
  internal/timeout/timeout_test.go
Labels: release-note-action-required

#2915 makefile: Enable creating ExtensionService CRD yaml
  Makefile
  apis/projectcontour/v1alpha1/register.go
  cmd/contour/serve.go
  examples/contour/01-crds.yaml
  examples/render/contour.yaml
  internal/k8s/informers.go
  site/docs/main/api-reference.html
Labels: release-note

#2913 apis: add kubebuilder regex validation for timeout strings
  apis/projectcontour/v1/httpproxy.go
  examples/contour/01-crds.yaml
  examples/render/contour.yaml
  internal/timeout/validation_test.go
  site/docs/main/api-reference.html
Labels: release-note

#2916 examples: generate v1 CustomResourceDefinitions
  README.md
  cmd/contour/serve.go
  examples/contour/01-crds.yaml
  examples/contour/02-role-contour.yaml
  examples/render/contour.yaml
  hack/generate-crd-yaml.sh
Labels: release-note, release-note-action-required

#2935 site/docs: add Envoy debug logging section to troubleshooting
  site/docs/main/troubleshooting.md
Labels: area/documentation

#2894 internal/envoy: Set the dns lookup family on externalName type clusters
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/envoy/v2/cluster.go
  internal/envoy/v2/cluster_test.go
  site/docs/main/api-reference.html
  site/docs/main/configuration.md
Labels: release-note

#2890 internal: add HTTProxy CORS support
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  examples/contour/01-crds.yaml
  examples/render/contour.yaml
  internal/contour/v2/route.go
  internal/contour/v2/route_test.go
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/envoy/v2/listener.go
  internal/envoy/v2/listener_test.go
  internal/envoy/v2/route.go
  internal/envoy/v2/route_test.go
  internal/featuretests/corspolicy_test.go
  internal/timeout/timeout.go
  internal/timeout/timeout_test.go
  site/docs/main/api-reference.html
Labels: release-note

#2910 Implement client authentication for backend TLS
  _integration/testsuite/fixtures/ingress-conformance-echo.yaml
  _integration/testsuite/httpproxy/013-backend-tls.yaml
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/extension_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/envoy/v2/auth.go
  internal/envoy/v2/auth_test.go
  internal/envoy/v2/cluster.go
  internal/envoy/v2/cluster_test.go
  internal/envoy/v2/socket_test.go
  internal/featuretests/backendcavalidation_test.go
  internal/featuretests/backendclientauth_test.go
  internal/featuretests/envoy.go
  internal/featuretests/externalname_test.go
  internal/featuretests/headerpolicy_test.go
  internal/featuretests/tcpproxy_test.go
  internal/featuretests/upstreamprotocol_test.go
  internal/xdscache/v2/secret.go
  site/docs/main/configuration.md
  site/docs/main/httpproxy.md
Labels: release-note
