Repository projectcontour/contour, pull requests merged in 2021-05, with the labels that each got.

#3642 cmd/contour: Remove deprecated flag 'experimental-service-apis'
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  site/docs/main/configuration.md
Labels: release-note, release-note-action-required

#3650 interna/k8s: Remove v1beta1 usage
  cmd/contour/ingressstatus.go
  cmd/contour/serve.go
  internal/k8s/clients_test.go
  internal/k8s/helpers.go
  internal/k8s/informers.go
  internal/k8s/kind.go
  internal/k8s/kind_test.go
  internal/k8s/scheme.go
  internal/k8s/statusaddress.go
  internal/k8s/statusaddress_test.go
Labels: release-note, release-note-action-required

#3671 update Envoy to v1.18.3
  Makefile
  examples/contour/03-envoy.yaml
  examples/render/contour.yaml
  site/_resources/compatibility-matrix.md
Labels: release-note

#3661 Do not ignore CA when downstream skip verify is true
  apis/projectcontour/v1/httpproxy.go
  examples/contour/01-crds.yaml
  examples/render/contour.yaml
  internal/dag/builder_test.go
  internal/dag/httpproxy_processor.go
  internal/envoy/v3/listener_test.go
  internal/featuretests/v3/downstreamvalidation_test.go
  site/docs/main/config/api-reference.html
  site/docs/main/config/tls-termination.md
  test/e2e/httpproxy/007_client_cert_auth_test.go
Labels: release-note

#3627 internal: Adds support for TLSRoute
  _integration/testsuite/fixtures/ingress-conformance-echo.yaml
  _integration/testsuite/gatewayapi/008-tlsroute.yaml
  internal/dag/builder_test.go
  internal/dag/cache.go
  internal/dag/gatewayapi_processor.go
  internal/dag/gatewayapi_processor_test.go
  internal/dag/status_test.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/featuretests/v3/tlsroute_test.go
  internal/status/conditions.go
Labels: release-note

#3659 Implements GatewayClass Controller
  cmd/contour/serve.go
  examples/contour/01-contour-config.yaml
  examples/contour/02-role-contour.yaml
  examples/gateway/00-gatewayclass.yaml
  examples/render/contour.yaml
  internal/controller/gatewayclass.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/errors/errors.go
  internal/errors/errors_test.go
  internal/k8s/informers.go
  internal/status/conditions.go
  internal/status/conditions_test.go
  internal/status/gatewayclass.go
  internal/validation/gatewayclass.go
  internal/validation/gatewayclass_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
Labels: release-note

#3728 move cert-contour.ext, cert-envoy.ext to certs/
  Makefile
  certs/cert-contour.ext
  certs/cert-envoy.ext
  site/content/docs/main/grpc-tls-howto.md
Labels: do not merge
