Repository projectcontour/contour, pull requests merged in 2021-06, with the labels that each got.

#3750 Refactor Makefile and update local dev options
  Makefile
Labels: release-note

#3827 pkg/config: Mark Gateway.Name & Gateway.Namespace as deprecated
  cmd/contour/serve.go
  pkg/config/parameters.go
  site/content/docs/main/configuration.md
Labels: kind/deprecation, release-note, release-note-action-required

#3801 internal/dag: Implement TLSRoute mode:terminate
  internal/dag/builder_test.go
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
  internal/featuretests/v3/httproute_test.go
  internal/featuretests/v3/tlsroute_test.go
  test/e2e/gateway/008_tlsroute_test.go
  test/e2e/gateway/gateway_test.go
Labels: release-note

#3773 Adds Controller Runtime Test Suite
  .github/workflows/prbuild.yaml
  hack/actions/install-kubernetes-toolchain.sh
  internal/controller/gatewayclass.go
  internal/controller/gatewayclass_test.go
  internal/controller/suite_test.go
Labels: area/gateway-api
