Repository projectcontour/contour, pull requests merged in 2021-08, with the labels that each got.

#3938 internal/dag: support TLSRoute weighted ForwardTos
  internal/dag/builder_test.go
  internal/dag/gatewayapi_processor.go
  internal/featuretests/v3/routeweight_test.go
Labels: release-note, area/gateway-api

#3953 updates for Kubernetes 1.22
  .github/workflows/prbuild.yaml
  examples/contour/01-crds.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  hack/actions/install-kubernetes-toolchain.sh
  site/content/resources/compatibility-matrix.md
  test/e2e/ingress/ensure_v1beta1_test.go
  test/e2e/ingress/ingress_test.go
  test/scripts/make-kind-cluster.sh
Labels: release-note

#3934 use unix socket for Envoy admin webpage
  cmd/contour/bootstrap.go
  cmd/contour/contour.go
  cmd/contour/serve.go
  cmd/contour/shutdownmanager.go
  cmd/contour/shutdownmanager_test.go
  examples/contour/01-contour-config.yaml
  examples/contour/03-envoy.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/envoy/bootstrap.go
  internal/envoy/bootstrap_test.go
  internal/envoy/v3/bootstrap.go
  internal/envoy/v3/bootstrap_test.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/stats.go
  internal/featuretests/v3/authorization_test.go
  internal/featuretests/v3/backendcavalidation_test.go
  internal/featuretests/v3/downstreamvalidation_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/featuretests.go
  internal/featuretests/v3/globalratelimit_test.go
  internal/featuretests/v3/listeners_test.go
  internal/featuretests/v3/localratelimit_test.go
  internal/featuretests/v3/rootnamespaces_test.go
  internal/featuretests/v3/routeweight_test.go
  internal/featuretests/v3/tcpproxy_test.go
  internal/featuretests/v3/tlscertificatedelegation_test.go
  internal/featuretests/v3/tlsroute_test.go
  internal/featuretests/v3/wildcardhost_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/server_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  test/e2e/deployment.go
  test/e2e/framework.go
  test/e2e/http.go
  test/e2e/infra/admin_test.go
  test/e2e/infra/infra_test.go
  test/e2e/infra/metrics_test.go
  test/e2e/kubectl.go
  test/scripts/kind-expose-port.yaml
Labels: release-note

#3984 drop obsolete DynamicClientHandler
  cmd/contour/serve.go
  internal/k8s/converter.go
  internal/k8s/converter_test.go
Labels: kind/cleanup
