Repository projectcontour/contour, pull requests merged in 2021-02, with the labels that each got.

#3269 Dynamic service headers
  _integration/testsuite/httpproxy/016-dynamic-headers.yaml
  internal/dag/builder_test.go
  internal/dag/httpproxy_processor.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  site/docs/main/config/request-rewriting.md
Labels: release-note

#3300 Revert "internal/envoy: disabled rest of the CBC mode ciphers (#3237)"
  internal/envoy/auth.go
  internal/envoy/v3/listener_test.go
Labels: release-note

#3301 Revert "Disable ECDHE-RSA-AES128-SHA and ECDHE-RSA-AES256-SHA ciphers (#3154)"
  internal/envoy/auth.go
  internal/envoy/v3/listener_test.go
Labels: release-note

#3296 internal: use metav1.Object for metadata access
  internal/annotation/annotations.go
  internal/annotation/annotations_test.go
  internal/dag/cache.go
  internal/dag/httpproxy_processor.go
  internal/dag/status.go
  internal/k8s/objectmeta.go
  internal/k8s/statusaddress.go
  internal/status/cache.go
Labels: kind/cleanup

#3293 internal/envoy: Set XffNumTrustedHops to keep header proto intact
  cmd/contour/serve.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/featuretests/v3/backendcavalidation_test.go
  internal/featuretests/v3/downstreamvalidation_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/listeners_test.go
  internal/featuretests/v3/localratelimit_test.go
  internal/featuretests/v3/rootnamespaces_test.go
  internal/featuretests/v3/tcpproxy_test.go
  internal/featuretests/v3/tlscertificatedelegation_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/docs/main/configuration.md
Labels: release-note

#3213 design: Service APIs implementation
  design/service-apis-implementation.md
Labels: kind/design

#3311 cmd/contour: Deprecate 'UseExperimentalServiceAPITypes' flag
  cmd/contour/serve.go
  cmd/contour/servecontext.go
Labels: release-note

#3330 Update usage of deprecated field FileAccessLog.json_format
  internal/envoy/v3/accesslog.go
  internal/envoy/v3/accesslog_test.go
Labels: release-note

#3316 internal/envoy: Expose Envoy's delayed_close_timeout
  cmd/contour/serve.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/docs/main/configuration.md
Labels: release-note

#3321 internal: update HTTP/2 protocol options config
  .golangci.yml
  internal/envoy/v3/auth.go
  internal/envoy/v3/bootstrap.go
  internal/envoy/v3/bootstrap_test.go
  internal/envoy/v3/cluster.go
  internal/envoy/v3/cluster_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/externalname_test.go
  internal/xdscache/v3/cluster_test.go
Labels: release-note

#3334 admin: Updates the PR template so that the text is visible
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: doc-impact

#3292 Add global TLS cipher suites configurability
  cmd/contour/serve.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/annotation/annotations_test.go
  internal/envoy/accesslog.go
  internal/envoy/auth.go
  internal/envoy/v3/auth.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/socket_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/listeners_test.go
  internal/featuretests/v3/tlsprotocolversion_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  internal/xdscache/v3/visitor_test.go
  pkg/config/ciphersuites.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/docs/main/configuration.md
Labels: release-note

#3322 Promlint fixes
  examples/grafana/02-grafana-configmap.yaml
  hack/generate-metrics-doc.go
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  site/_metrics/contour_httpproxy.md
  site/_metrics/contour_httpproxy_invalid.md
  site/_metrics/contour_httpproxy_invalid_total.md
  site/_metrics/contour_httpproxy_orphaned.md
  site/_metrics/contour_httpproxy_orphaned_total.md
  site/_metrics/contour_httpproxy_root.md
  site/_metrics/contour_httpproxy_root_total.md
  site/_metrics/contour_httpproxy_total.md
  site/_metrics/contour_httpproxy_valid.md
  site/_metrics/contour_httpproxy_valid_total.md
Labels: release-note, release-note-action-required

#3359 internal/dag: Log error when service not found
  internal/dag/ingress_processor.go
Labels: kind/cleanup

#3358 Apply correct image pull policy when running ingress conformance
  _integration/testsuite/run-ingress-conformance.sh
Labels: kind/cleanup

#3145 design: Design for HTTPProxy Conflict Resolution
  design/httpproxy-conflict.md
Labels: kind/design

#3298 add global rate limiting support
  Makefile
  _integration/testsuite/httpproxy/020-global-rate-limiting.yaml
  _integration/testsuite/install-ratelimit-service.sh
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  cmd/contour/serve.go
  examples/contour/01-contour-config.yaml
  examples/contour/01-crds.yaml
  examples/ratelimit/01-ratelimit-config.yaml
  examples/ratelimit/02-ratelimit.yaml
  examples/ratelimit/03-ratelimit-extsvc.yaml
  examples/ratelimit/04-contour-config.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/extension_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  internal/envoy/v3/ratelimit.go
  internal/envoy/v3/ratelimit_test.go
  internal/envoy/v3/route.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/globalratelimit_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/route.go
  pkg/config/parameters.go
  site/_guides/global-rate-limiting.md
  site/docs/main/config/api-reference.html
  site/docs/main/config/rate-limiting.md
  site/docs/main/configuration.md
Labels: release-note

#3383 site/docs: Fix TLS Ciphers defaults link
  site/docs/main/configuration.md
Labels: area/documentation

#3304 Re-disable insecure AES128/256 ciphers by default
  pkg/config/ciphersuites.go
Labels: release-note, release-note-action-required

#3314 envoy listener exact balancer
  cmd/contour/serve.go
  internal/xdscache/v3/listener.go
  pkg/config/parameters.go
  site/docs/main/configuration.md
Labels: release-note

#3394 Adds Gateway API User Guide
  netlify.toml
  site/_guides/gateway-api.md
Labels: release-note
