Repository projectcontour/contour, pull requests merged in 2021-09, with the labels that each got.

#3992 use the oldest Gateway for the controlled+admitted GatewayClass
  cmd/contour/serve.go
  internal/controller/gateway.go
  internal/controller/gatewayclass.go
  internal/k8s/helpers.go
  test/e2e/gateway/multiple_gatewayclass_test.go
  test/e2e/gateway/multiple_gateways_and_classes_test.go
Labels: release-note

#4014 docs: GatewayConfig updates
  site/content/docs/main/configuration.md
  site/content/docs/v1.17.0/configuration.md
  site/content/docs/v1.17.1/configuration.md
  site/content/docs/v1.17.2/configuration.md
  site/content/docs/v1.18.0/configuration.md
  site/content/docs/v1.18.1/configuration.md
Labels: area/documentation

#4010 use GHCR image by default
  .github/workflows/build_main.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/prbuild.yaml
  CONTRIBUTING.md
  Makefile
  examples/contour/02-job-certgen.yaml
  examples/contour/03-contour.yaml
  examples/contour/03-envoy.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  hack/release/make-release-tag.sh
  site/content/docs/main/redeploy-envoy.md
  site/content/examples/authdemo/02-certsjob.yaml
  test/scripts/install-contour-working.sh
Labels: release-note

#3989 design: Add configuration & deployment crd design
  design/configuration-crd.md
Labels: kind/design

#3824 internal: program 502/503 routes for misconfigured services and includes
  internal/dag/builder_test.go
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
  internal/featuretests/v3/tcpproxy_test.go
  internal/xdscache/v3/route_test.go
Labels: release-note

#3958 Add quarterly release proposal
  design/quarterly-release.md
Labels: release-note

#4019 Add changelog design proposal
  design/changelog.md
Labels: kind/design

#3988 doc: program 502/503 routes for misconfigured services and includes
  site/content/docs/main/config/fundamentals.md
Labels: area/documentation

#4038 internal/dag: Add additional validation for fqdn
  apis/projectcontour/v1/httpproxy.go
  examples/contour/01-crds.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
  test/e2e/framework.go
  test/e2e/httpproxy/fqdn_test.go
  test/e2e/httpproxy/httpproxy_test.go
Labels: release-note

#4037 Deprecate the static cluster `service-stats`
  cmd/contour/shutdownmanager_test.go
  internal/envoy/v3/bootstrap.go
  internal/envoy/v3/bootstrap_test.go
  internal/envoy/v3/stats.go
  internal/envoy/v3/stats_test.go
Labels: release-note, release-note-action-required

#4051 test/e2e: replace httpbin with ingress echoserver
  test/e2e/fixtures.go
  test/e2e/framework.go
  test/e2e/httpproxy/http_health_checks_test.go
Labels: kind/cleanup, area/testing

#4026 Update documentation for transition to quarterly releases
  RELEASES.md
  site/content/docs/main/github.md
  site/content/docs/v1.18.1/github.md
  site/content/resources/support.md
  site/content/resources/tagging.md
Labels: release-note

#4055 test/e2e: speed up HTTPProxy external name test
  test/e2e/httpproxy/external_name_test.go
Labels: kind/cleanup, area/testing

#4053 cmd/contour: remove legacy CRD validation code
  cmd/contour/serve.go
  examples/contour/02-role-contour.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: kind/cleanup
