Repository projectcontour/contour, pull requests merged in 2021-07, with the labels that each got.

#3852 internal/xdscache: ignore irrelevant Endpoints
  internal/xdscache/v3/endpointstranslator.go
  internal/xdscache/v3/endpointstranslator_test.go
Labels: release-note

#3887 update Envoy to 1.19.0
  Makefile
  examples/contour/03-envoy.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
Labels: release-note

#3868 internal/dag: Add tests for Gateway status
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
  internal/status/gatewayconditions.go
Labels: area/testing

#3894 internal/dag: allow delegation of upstream validation CACertificate
  apis/projectcontour/v1/httpproxy.go
  examples/contour/01-crds.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/builder_test.go
  internal/dag/cache.go
  internal/dag/extension_processor.go
  internal/dag/httpproxy_processor.go
  internal/featuretests/v3/extensionservice_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/upstream-tls.md
Labels: release-note

#3902 HTTPProxy: add Spec.IngressClassName
  apis/projectcontour/v1/httpproxy.go
  examples/contour/01-crds.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/annotation/annotations.go
  internal/annotation/annotations_test.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/featuretests/v3/ingressclass_test.go
  internal/ingressclass/ingressclass.go
  internal/ingressclass/ingressclass_test.go
  internal/k8s/statusaddress.go
  internal/k8s/statusaddress_test.go
  internal/validation/ingress/ingress.go
  internal/validation/ingress/ingress_test.go
  site/content/docs/main/config/annotations.md
  site/content/docs/main/config/api-reference.html
Labels: kind/api-change, release-note

#3694 internal/envoy: configurable access log format
  cmd/contour/serve.go
  examples/contour/01-contour-config.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  internal/envoy/v3/accesslog.go
  internal/envoy/v3/accesslog_test.go
  internal/envoy/v3/listener_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/globalratelimit_test.go
  internal/featuretests/v3/listeners_test.go
  internal/featuretests/v3/timeouts_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  internal/xdscache/v3/visitor_test.go
  pkg/config/accesslog.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/configuration.md
Labels: release-note

#3913 Kindly running post - fix broken links
  site/content/posts/2019-07-11-kindly-running-contour.md
Labels: area/website

#3904 internal/controller: switch to using event predicates for filtering
  internal/controller/gateway.go
  internal/controller/gatewayclass.go
Labels: kind/cleanup

#3935 internal/envoy: fix TCPProxy weights bug
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
Labels: release-note
