Repository projectcontour/contour, pull requests merged in 2021-01, with the labels that each got.

#3224 site: rewrite release instructions
  site/_resources/release-process.md
Labels: area/documentation

#3237 internal/envoy: disabled rest of the CBC mode ciphers
  internal/envoy/auth.go
  internal/envoy/v3/listener_test.go
Labels: area/tls

#3231 Do a case insensitive match when checking for duplicate FQDNs
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
Labels: do not merge, release-note, release-note-action-required

#3245 Bump to Envoy 1.17.0
  Makefile
  examples/contour/03-envoy.yaml
  examples/render/contour.yaml
Labels: release-note

#3236 Support specific Envoy dynamic request headers
  _integration/testsuite/httpproxy/016-dynamic-headers.yaml
  _integration/testsuite/policies/contour-expect.rego
  internal/dag/builder_test.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  site/docs/main/config/request-rewriting.md
Labels: release-note

#3265 drop all TLS 1.1 references
  apis/projectcontour/v1/httpproxy.go
  examples/contour/01-contour-config.yaml
  examples/contour/01-crds.yaml
  examples/render/contour.yaml
  internal/annotation/annotations.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/socket_test.go
  internal/envoy/v3/tls.go
  site/docs/main/config/api-reference.html
  site/docs/main/config/tls-termination.md
  site/docs/main/configuration.md
Labels: release-note, release-note-action-required

#3248 Enable allow_chunked_length by default with config override
  cmd/contour/serve.go
  examples/contour/01-contour-config.yaml
  examples/render/contour.yaml
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/docs/main/configuration.md
Labels: release-note

#3282 Add support for header hash based load balancing
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  apis/projectcontour/v1alpha1/extensionservice.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  design/loadbalancer-hash-policy-design.md
  examples/contour/01-crds.yaml
  examples/example-workload/httpproxy/03-routes/httpproxy-lb-request-hash.yaml
  examples/render/contour.yaml
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/extension_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  internal/envoy/v3/cluster.go
  internal/envoy/v3/cluster_test.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/extensionservice_test.go
  internal/featuretests/v3/loadbalancerpolicy_test.go
  internal/featuretests/v3/tcpproxy_test.go
  internal/xdscache/v3/cluster_test.go
  site/docs/main/config/api-reference.html
  site/docs/main/config/request-routing.md
Labels: release-note
