Repository projectcontour/contour, pull requests merged in 2022-10, with the labels that each got.

#4768 Updates for release-candidate release process
  hack/release/prepare-release.go
  site/content/resources/release-process.md
Labels: release-note/none-required

#4770 test/e2e: Gateway tests run in "gateway" reconcile mode by default
  .github/workflows/build_daily.yaml
  Makefile
  test/e2e/gateway/gateway_test.go
Labels: release-note/none-required

#4765 Remove e2e gateway tests that overlap with Gateway API conformance
  test/e2e/gateway/gateway_allow_type_test.go
  test/e2e/gateway/gateway_test.go
  test/e2e/gateway/header_condition_match_test.go
  test/e2e/gateway/invalid_backend_ref_test.go
  test/e2e/gateway/query_param_match_test.go
  test/e2e/gateway/request_header_modifier_test.go
Labels: release-note/none-required

#4773 Bump golang to 1.19.2
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/4773-sunjayBhatia-small.md
Labels: release-note/small

#4774 test/scripts: add retry loop for metallb config
  test/scripts/make-kind-cluster.sh
Labels: release-note/none-required

#4777 add optional DNS lookup family for remote JWKS
  apis/projectcontour/v1/httpproxy.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
  internal/featuretests/v3/jwtverification_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/none-required

#4781 fixes to enable development on arm64
  Dockerfile
  test/e2e/fixtures.go
  test/scripts/make-kind-cluster.sh
Labels: release-note/none-required

#4782 Enable HTTPRouteQueryParamMatching and HTTPRouteMethodMatching in main conformance tests
  test/scripts/run-gateway-conformance.sh
Labels: release-note/none-required

#4791 Update the Community Page on the Website
  site/content/community/_index.html
Labels: Hacktoberfest, release-note/none-required, hacktoberfest-accepted

#4789 add ForwardJWT option
  apis/projectcontour/v1/httpproxy.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/envoy/v3/listener.go
  internal/featuretests/v3/jwtverification_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/jwt-verification.md
Labels: release-note/none-required

#4680 crd/ContourDeployment: Add fields 'extraVolumes & extraVolumeMounts'
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/contourdeployment.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/4680-izturn-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gatewayclass.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small

#4783 Fix workgroup AddContext bug
  internal/workgroup/group.go
  internal/workgroup/group_test.go
Labels: release-note/none-required

#4681 crd/ContourDeployment: Add field 'podAnnotations'
  apis/projectcontour/v1alpha1/contourdeployment.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/4681-izturn-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small

#4798 Update API doc generation links to recent k8s version
  hack/api-docs-config/refdocs/config.json
  site/content/docs/main/config/api-reference.html
Labels: release-note/none-required

#4712 crd/ContourDeployment: Add fields for resource quotas
  apis/projectcontour/v1alpha1/contourdeployment.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/4712-izturn-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  internal/provisioner/objects/deployment/deployment.go
  internal/provisioner/objects/deployment/deployment_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small

#4804 update Envoy to v1.24.0
  Makefile
  changelogs/unreleased/4804-skriss-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/small

#4808 Update netlify redirects for latest release (1.23)
  netlify.toml
Labels: release-note/none-required

#4810 test/scripts: remove unneeded steps from install-contour-working.sh
  test/scripts/install-contour-working.sh
Labels: release-note/none-required

#4811 use Docker cache mounts for go build & mod cache
  Dockerfile
Labels: release-note/none-required

#4796 Add support for optional certificate validation
  apis/projectcontour/v1/httpproxy.go
  changelogs/unreleased/4796-gautierdelorme-minor.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/envoy/v3/auth.go
  internal/envoy/v3/listener_test.go
  internal/featuretests/v3/downstreamvalidation_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/tls-termination.md
  test/e2e/httpproxy/client_cert_auth_test.go
Labels: release-note/minor

#4797 XFCC header support
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  changelogs/unreleased/4797-gautierdelorme-minor.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/featuretests/v3/downstreamvalidation_test.go
  internal/featuretests/v3/envoy.go
  internal/xdscache/v3/listener.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/tls-termination.md
Labels: release-note/minor

#4805 replaces github.com/golang/protobuf with google.golang.org/protobuf
  .golangci.yml
  go.mod
  internal/envoy/bootstrap.go
  internal/envoy/route.go
  internal/envoy/v3/accesslog.go
  internal/envoy/v3/accesslog_test.go
  internal/envoy/v3/auth.go
  internal/envoy/v3/bootstrap.go
  internal/envoy/v3/bootstrap_test.go
  internal/envoy/v3/cluster.go
  internal/envoy/v3/cluster_test.go
  internal/envoy/v3/endpoint.go
  internal/envoy/v3/healthcheck.go
  internal/envoy/v3/healthcheck_test.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/ratelimit.go
  internal/envoy/v3/ratelimit_test.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  internal/envoy/v3/stats.go
  internal/envoy/v3/stats_test.go
  internal/featuretests/v3/authorization_test.go
  internal/featuretests/v3/cluster_test.go
  internal/featuretests/v3/corspolicy_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/externalname_test.go
  internal/featuretests/v3/featuretests.go
  internal/featuretests/v3/headerpolicy_test.go
  internal/featuretests/v3/jwtverification_test.go
  internal/featuretests/v3/localratelimit_test.go
  internal/featuretests/v3/routeweight_test.go
  internal/protobuf/helpers.go
  internal/protobuf/helpers_test.go
  internal/sorter/sorter_test.go
  internal/xds/resource.go
  internal/xds/v3/contour.go
  internal/xds/v3/contour_test.go
  internal/xdscache/v3/cluster.go
  internal/xdscache/v3/cluster_test.go
  internal/xdscache/v3/endpointstranslator.go
  internal/xdscache/v3/endpointstranslator_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  internal/xdscache/v3/route.go
  internal/xdscache/v3/route_test.go
  internal/xdscache/v3/runtime.go
  internal/xdscache/v3/runtime_test.go
  internal/xdscache/v3/secret.go
  internal/xdscache/v3/secret_test.go
  test/e2e/httpproxy/grpc_test.go
Labels: release-note/none-required

#4795 Update dag.go
  internal/dag/dag.go
Labels: release-note/none-required

#4788 internal/dag: validate Secrets only when used
  changelogs/unreleased/4788-skriss-minor.md
  internal/dag/builder_test.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/dag/dag.go
  internal/dag/extension_processor.go
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/dag/secret.go
  internal/dag/secret_test.go
  internal/dag/status_test.go
  internal/featuretests/v3/backendcavalidation_test.go
  internal/featuretests/v3/backendclientauth_test.go
  internal/featuretests/v3/downstreamvalidation_test.go
  internal/featuretests/v3/extensionservice_test.go
  internal/featuretests/v3/jwtverification_test.go
Labels: release-note/minor

#4792 Secret updates/deletes only trigger DAG rebuilds if referenced
  changelogs/unreleased/4792-skriss-small.md
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/featuretests/v3/backendclientauth_test.go
  internal/featuretests/v3/fallbackcert_test.go
  internal/featuretests/v3/secrets_test.go
Labels: release-note/small

#4799 allow TLS secrets to be of type Opaque
  changelogs/unreleased/4799-skriss-small.md
  internal/dag/secret.go
  internal/dag/secret_test.go
Labels: release-note/small

#4818 drop internal/workgroup package
  cmd/contour/serve.go
  internal/featuretests/v3/featuretests.go
  internal/httpsvc/http.go
  internal/httpsvc/http_test.go
  internal/workgroup/example_test.go
  internal/workgroup/group.go
  internal/workgroup/group_test.go
Labels: release-note/none-required

#4821 update golangci-lint version and action version
  .github/workflows/prbuild.yaml
  cmd/contour/shutdownmanager.go
  hack/golangci-lint
Labels: release-note/none-required

#4822 Handle Envoy 1.24 Deprecations
  changelogs/unreleased/4822-sunjayBhatia-small.md
  go.mod
  go.sum
  internal/envoy/v3/ratelimit_test.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  internal/featuretests/v3/corspolicy_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/headerpolicy_test.go
  internal/featuretests/v3/localratelimit_test.go
  internal/featuretests/v3/routeweight_test.go
  internal/xdscache/v3/route_test.go
Labels: release-note/small

#4824 Fix upgrade from version tag finding
  test/scripts/get-contour-upgrade-from-version.sh
Labels: release-note/none-required

#4761 HTTPProxy: add healthCheck port config
  apis/projectcontour/v1/httpproxy.go
  changelogs/unreleased/4761-yangyy93-minor.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/accessors.go
  internal/dag/accessors_test.go
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/envoy/v3/cluster_test.go
  internal/envoy/v3/endpoint.go
  internal/envoy/v3/endpoint_test.go
  internal/xdscache/v3/endpointstranslator.go
  internal/xdscache/v3/endpointstranslator_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/health-checks.md
Labels: release-note/minor

#4828 Fix merge issue and move test helpers to be unexported in test file
  internal/envoy/v3/endpoint.go
  internal/envoy/v3/endpoint_test.go
  internal/xdscache/v3/endpointstranslator_test.go
Labels: release-note/none-required
