Repository projectcontour/contour, pull requests merged in 2022-11, with the labels that each got.

#4801 gateway provisioner: support changing Envoy log level
  apis/projectcontour/v1alpha1/contourdeployment.go
  changelogs/unreleased/4801-izturn-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gatewayclass.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  internal/provisioner/objects/deployment/deployment.go
  internal/provisioner/objects/deployment/deployment_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small

#4829 provisioner: move LogLevel validation to controller
  apis/projectcontour/v1alpha1/contourdeployment.go
  internal/provisioner/controller/gatewayclass.go
Labels: release-note/none-required

#4827 Service updates/deletes only trigger DAG rebuilds if referenced by an HTTPProxy
  changelogs/unreleased/4827-Vishal-Chdhry-small.md
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/featuretests/v3/cluster_test.go
  internal/featuretests/v3/featuretests.go
Labels: release-note/small

#4803 crd/ContourDeployment: Add field for set externalTrafficPolicy for service/envoy
  apis/projectcontour/v1alpha1/contourdeployment.go
  changelogs/unreleased/4803-izturn-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/controller/gatewayclass.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/service/service.go
  internal/provisioner/objects/service/service_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small

#4767 internal/provisioner: use generics for Ensure functions
  CONTRIBUTING.md
  go.mod
  go.sum
  internal/provisioner/objects/contourconfig/contourconfig.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/deployment/deployment.go
  internal/provisioner/objects/object.go
  internal/provisioner/objects/object_test.go
  internal/provisioner/objects/rbac/clusterrole/cluster_role.go
  internal/provisioner/objects/rbac/clusterrolebinding/cluster_role_binding.go
  internal/provisioner/objects/rbac/rbac.go
  internal/provisioner/objects/rbac/role/role.go
  internal/provisioner/objects/rbac/rolebinding/role_binding.go
  internal/provisioner/objects/rbac/serviceaccount/service_account.go
  internal/provisioner/objects/service/service.go
Labels: release-note/none-required

#4830 [dev-gwapi-0.6] drop support for ReferencePolicy
  changelogs/unreleased/4830-skriss-deprecation.md
  cmd/contour/serve.go
  examples/contour/02-role-contour.yaml
  examples/gateway-provisioner/01-roles.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/cache.go
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
  internal/k8s/rbac.go
  internal/provisioner/objects/rbac/clusterrole/cluster_role.go
Labels: release-note/deprecation

#4842 remove daily Gateway API conformance run
  .github/workflows/build_daily.yaml
Labels: release-note/none-required

#4850 test/e2e/httpproxy: Remove gRPC test flake attempts
  test/e2e/httpproxy/grpc_test.go
Labels: release-note/none-required

#4846 Fix: ExtensionServices are updated continuously by contour
  changelogs/unreleased/4846-Vishal-Chdhry-small.md
  internal/contour/handler.go
  internal/k8s/helpers.go
Labels: release-note/small

#4856 Bump Go to 1.19.3
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/4856-sunjayBhatia-small.md
Labels: release-note/small

#4857 Bump kind images and k8s api deps
  .github/workflows/prbuild.yaml
  go.mod
  go.sum
  hack/actions/install-kubernetes-toolchain.sh
  test/scripts/make-kind-cluster.sh
Labels: release-note/none-required

#4855 Create welcome-new-contributors.yaml
  .github/workflows/welcome-new-contributors.yaml
Labels: release-note/none-required

#4858 Bump ginkgo, gomega, other test/tooling deps
  Makefile
  go.mod
  go.sum
  hack/actions/check-changefile-exists.go
  hack/actions/install-kubernetes-toolchain.sh
  internal/controller/mocks/manager.go
  internal/debug/mocks/dag_builder.go
  internal/k8s/mocks/cache.go
  internal/leadership/mocks/need_leader_election_notification.go
Labels: release-note/none-required

#4859 Bump controller-runtime/tools
  examples/contour/01-crds.yaml
  examples/contour/02-role-contour.yaml
  examples/gateway-provisioner/01-roles.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  internal/dag/cache_test.go
  internal/k8s/mocks/cache.go
Labels: release-note/none-required

#4861 Add dependabot dependency update configuration
  .github/dependabot.yml
Labels: release-note/none-required

#4867 Ignore prbuild workflow for dependabot branches on push
  .github/workflows/prbuild.yaml
Labels: release-note/none-required

#4868 Update codeql workflow to v2
  .github/workflows/codeql-analysis.yml
Labels: release-note/none-required

#4872 update to cert-manager v1.10.1
  go.mod
  go.sum
  test/e2e/certs.go
  test/e2e/framework.go
  test/e2e/httpproxy/backend_tls_test.go
  test/e2e/httpproxy/client_cert_auth_test.go
  test/e2e/httpproxy/httpproxy_test.go
  test/e2e/ingress/backend_tls_test.go
  test/e2e/ingress/ingress_test.go
  test/scripts/make-kind-cluster.sh
Labels: area/dependency, release-note/none-required

#4873 Add trivy scan workflow
  .github/workflows/trivy-scan.yaml
  site/content/resources/release-process.md
Labels: release-note/none-required

#4875 Use correct trivy tag version
  .github/workflows/trivy-scan.yaml
Labels: release-note/none-required

#4876 trivy: Only perform vulnerability scanning
  .github/workflows/trivy-scan.yaml
Labels: release-note/none-required

#4879 trivy: Use matrix/ref checkout in scheduled runs
  .github/workflows/trivy-scan.yaml
Labels: release-note/none-required

#4882 Dependency updates for release-1.22
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  go.mod
  go.sum
Labels: release-note/none-required

#4884 release-1.22: Bump module go version and golang/x/crypto
  cmd/contour/certgen_test.go
  cmd/contour/cli.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  cmd/contour/shutdownmanager_test.go
  go.mod
  go.sum
  hack/release/prepare-release.go
  internal/dag/policy_test.go
  internal/httpsvc/http.go
  internal/httpsvc/http_test.go
  internal/xds/v3/contour_test.go
  internal/xdscache/v3/server_test.go
  test/e2e/deployment.go
  test/e2e/fixtures.go
  test/e2e/http.go
Labels: release-note/none-required
