Repository projectcontour/contour, pull requests merged in 2022-01, with the labels that each got.

#4255 don't set issues to stale or close them
  .github/workflows/stale.yaml
Labels: release-note/none-required

#4247 test/scripts: Add script to deploy gcp benchmarking cluster
  test/scripts/gcp-bench-cluster.sh
Labels: release-note/none-required

#4256 Add Knative as adopter
  ADOPTERS.md
  site/img/adopters/VMware-logo-grey.jpg
  site/img/adopters/knative.svg
Labels: release-note/none-required

#4259 update to Ginkgo v2.0.0
  go.mod
  go.sum
  hack/actions/install-kubernetes-toolchain.sh
  test/e2e/certs.go
  test/e2e/fixtures.go
  test/e2e/framework.go
  test/e2e/gateway/gateway_allow_type_test.go
  test/e2e/gateway/gateway_test.go
  test/e2e/gateway/header_condition_match_test.go
  test/e2e/gateway/host_rewrite_test.go
  test/e2e/gateway/invalid_forward_to_test.go
  test/e2e/gateway/multiple_gateways_and_classes_test.go
  test/e2e/gateway/path_condition_match_test.go
  test/e2e/gateway/request_header_modifier_test.go
  test/e2e/gateway/request_redirect_test.go
  test/e2e/gateway/tls_gateway_test.go
  test/e2e/gateway/tls_wildcard_host_test.go
  test/e2e/gateway/tlsroute_test.go
  test/e2e/http.go
  test/e2e/httpproxy/backend_tls_test.go
  test/e2e/httpproxy/client_cert_auth_test.go
  test/e2e/httpproxy/cookie_rewrite_test.go
  test/e2e/httpproxy/dynamic_headers_test.go
  test/e2e/httpproxy/external_auth_test.go
  test/e2e/httpproxy/external_name_test.go
  test/e2e/httpproxy/fqdn_test.go
  test/e2e/httpproxy/global_rate_limiting_test.go
  test/e2e/httpproxy/header_condition_match_test.go
  test/e2e/httpproxy/host_header_rewrite_test.go
  test/e2e/httpproxy/http_health_checks_test.go
  test/e2e/httpproxy/httpproxy_test.go
  test/e2e/httpproxy/https_fallback_certificate_test.go
  test/e2e/httpproxy/https_misdirected_request_test.go
  test/e2e/httpproxy/https_sni_enforcement_test.go
  test/e2e/httpproxy/include_prefix_condition_test.go
  test/e2e/httpproxy/local_rate_limiting_test.go
  test/e2e/httpproxy/merge_slash_test.go
  test/e2e/httpproxy/path_condition_match_test.go
  test/e2e/httpproxy/pod_restart_test.go
  test/e2e/httpproxy/request_redirect_test.go
  test/e2e/httpproxy/required_field_validation_test.go
  test/e2e/httpproxy/retry_policy_validation_test.go
  test/e2e/httpproxy/root_namespaces_test.go
  test/e2e/httpproxy/tcproute_https_termination_test.go
  test/e2e/incluster/incluster_test.go
  test/e2e/incluster/leaderelection_test.go
  test/e2e/incluster/rbac_test.go
  test/e2e/incluster/smoke_test.go
  test/e2e/infra/admin_test.go
  test/e2e/infra/infra_test.go
  test/e2e/infra/metrics_test.go
  test/e2e/ingress/backend_tls_test.go
  test/e2e/ingress/ingress_test.go
  test/e2e/ingress/long_path_match_test.go
  test/e2e/ingress/tls_wildcard_host_test.go
  test/e2e/upgrade/upgrade_test.go
Labels: release-note/none-required

#4257 hack/release: add release notes generation tool
  changelogs/unreleased/minor-sample.md
  changelogs/unreleased/small-sample.md
  hack/release/prepare-release.go
  hack/release/release-notes-template.md
  site/content/resources/release-process.md
Labels: release-note/none-required

#4100 Use envoy xds server type in daily e2e tests
  .github/workflows/build_daily.yaml
  test/e2e/deployment.go
  test/e2e/fixtures.go
  test/e2e/gateway/gateway_test.go
  test/e2e/gateway/multiple_gateways_and_classes_test.go
  test/e2e/httpproxy/httpproxy_test.go
  test/e2e/incluster/incluster_test.go
  test/e2e/infra/infra_test.go
  test/e2e/ingress/ingress_test.go
Labels: release-note/none-required

#4261 Kubernetes 1.23 updates
  .codespell.skip
  .github/workflows/prbuild.yaml
  changelogs/unreleased/4261-skriss-small.md
  go.mod
  go.sum
  hack/actions/install-kubernetes-toolchain.sh
  internal/controller/controller_test.go
  internal/controller/httproute.go
  internal/controller/mocks/manager.go
  internal/controller/tlsroute.go
  internal/k8s/log.go
  internal/k8s/log_test.go
  site/content/resources/compatibility-matrix.md
  test/e2e/fixtures.go
  test/e2e/httpproxy/cookie_rewrite_test.go
  test/scripts/make-kind-cluster.sh
  versions.yaml
Labels: release-note/small

#4263 update daily E2E run for Kubernetes 1.23
  .github/workflows/build_daily.yaml
Labels: release-note/none-required

#4264 remove dependency from daily build
  .github/workflows/build_daily.yaml
Labels: release-note/none-required

#4265 Simplify daily build
  .github/workflows/build_daily.yaml
Labels: release-note/none-required

#4266 internal/k8s: StatusUpdateWriter only writes to update channel when leader
  internal/k8s/status.go
  test/e2e/incluster/smoke_test.go
Labels: release-note/none-required

#4268 update Gateway API to v0.4.1
  changelogs/unreleased/4268-skriss-small.md
  examples/gateway/00-crds.yaml
  examples/render/contour-gateway.yaml
  go.mod
  go.sum
  internal/dag/builder_test.go
  internal/gatewayapi/helpers.go
  test/e2e/gateway/request_redirect_test.go
Labels: release-note/small

#4269 test/e2e: move Envoy deployment tests to daily build
  .github/workflows/build_daily.yaml
  test/e2e/deployment.go
  test/e2e/deployment/admin_test.go
  test/e2e/deployment/deployment_test.go
  test/e2e/deployment/metrics_test.go
  test/e2e/deployment/path_condition_match_test.go
  test/e2e/framework.go
  test/e2e/gateway/gateway_test.go
  test/e2e/httpproxy/httpproxy_test.go
  test/e2e/incluster/incluster_test.go
  test/e2e/infra/infra_test.go
  test/e2e/infra/metrics_test.go
  test/e2e/ingress/ingress_test.go
  test/e2e/upgrade/upgrade_test.go
Labels: release-note/none-required

#4281 internal/certgen: Fix error handling when writing to k8s
  changelogs/unreleased/4281-sunjayBhatia-small.md
  internal/certgen/certgen.go
Labels: release-note/small

#4262 site/guides: drop Gateway API v1alpha1 guide
  changelogs/unreleased/4122-skriss-docs.md
  changelogs/unreleased/4262-skriss-docs.md
  site/content/guides/gateway-api-v1alpha2.md
  site/content/guides/gateway-api.md
Labels: do not merge, release-note/docs

#4279 site: Add docs for header manipualtion with Ingress
  changelogs/unreleased/4279-sunjayBhatia-docs.md
  site/content/docs/main/config/ingress.md
  site/data/docs/main-toc.yml
Labels: release-note/docs

#4283 site: update ingress.md for tls-cert-namespace annotation
  site/content/docs/main/config/ingress.md
Labels: release-note/none-required

#4284 hack/release: allow GitHub usernames with '-'
  hack/release/prepare-release.go
Labels: release-note/none-required

#4286 test/e2e: enable retrying flaky tests
  test/e2e/httpproxy/global_rate_limiting_test.go
  test/e2e/infra/metrics_test.go
Labels: release-note/none-required

#4287 cmd/contour: pass ApplyToIngress flag to DAG processor
  changelogs/unreleased/4287-skriss-small.md
  cmd/contour/serve.go
  cmd/contour/serve_test.go
  test/e2e/ingress/headers_policy_test.go
  test/e2e/ingress/ingress_test.go
Labels: release-note/small

#4273 Bump Envoy to v1.21.0
  Makefile
  changelogs/unreleased/4075-sunjayBhatia-small.md
  changelogs/unreleased/4273-sunjayBhatia-small.md
  examples/contour/03-envoy.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  internal/envoy/v3/auth.go
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/small

#4299 Add Flyte as adopter
  ADOPTERS.md
  site/img/adopters/flyte.png
Labels: release-note/none-required, area/community

#4307 fix envoy deployment release stuff
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  hack/release/make-release-tag.sh
Labels: release-note/none-required

#4308 [release-1.20 branch] fix envoy deployment release
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  hack/release/make-release-tag.sh
Labels: release-note/none-required

#4312 cmd/contour: Disable unused listeners
  changelogs/unreleased/4312-sunjayBhatia-small.md
  cmd/contour/serve.go
Labels: release-note/small

#4252 Add CRL to http proxy client validation
  design/downstream-crl-design.md
Labels: release-note/none-required

#4251 test/e2e/bench: Add bench test suite
  Makefile
  go.mod
  go.sum
  test/e2e/bench/bench_test.go
  test/e2e/http.go
  test/scripts/gcp-bench-cluster.sh
Labels: release-note/none-required

#4304 internal/dag: don't check annotations for uncached objects
  changelogs/unreleased/4304-skriss-small.md
  internal/dag/cache.go
Labels: release-note/small

#4233 site: Add docs for Envoy deployment
  site/content/docs/main/architecture.md
  site/content/docs/main/deploy-options.md
  site/content/docs/main/img/contour_deployment_in_k8s.png
Labels: release-note/none-required

#4310 hack/actions: fix release image tag fetching
  hack/actions/build-and-push-release-images.sh
Labels: release-note/none-required

#4311 [release-1.20 branch] hack/actions: fix release image tag fetching
  hack/actions/build-and-push-release-images.sh
Labels: release-note/none-required

#4303 update netlify redirects for v1.20.0
  netlify.toml
Labels: release-note/none-required

#4313 site/docs: add Envoy deployment v1.20.0 docs
  site/content/docs/v1.20.0/architecture.md
  site/content/docs/v1.20.0/deploy-options.md
  site/content/docs/v1.20.0/img/contour_deployment_in_k8s.png
Labels: release-note/none-required
