Repository projectcontour/contour, pull requests merged in 2022-04, with the labels that each got.

#4440 internal/provisioner: set GatewayClass conditions correctly based on parametersRef
  apis/projectcontour/v1alpha1/contourdeployment.go
  apis/projectcontour/v1alpha1/register.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/4440-skriss-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/01-crds.yaml
  examples/gateway-provisioner/01-roles.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/controller/gatewayclass.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/provisioner/rbac/rbac.go
  site/content/docs/main/config/api-reference.html
  test/e2e/provisioner/provisioner_test.go
Labels: release-note/small

#4446 Each path in an Ingress is required to have a corresponding path type.
  changelogs/unreleased/4446-lou-lan-docs.md
  site/content/docs/main/config/fundamentals.md
  site/content/docs/main/config/virtual-hosts.md
  site/content/docs/v1.20.1/config/fundamentals.md
  site/content/docs/v1.20.1/config/virtual-hosts.md
Labels: release-note/docs

#4452 ci: run Gateway API conformance tests
  .github/workflows/prbuild.yaml
  Makefile
  test/scripts/run-gateway-conformance.sh
Labels: release-note/none-required

#4455 CI: set --contour-image when running Gateway API conformance
  test/scripts/run-gateway-conformance.sh
Labels: release-note/none-required

#4453 test/e2e: add flake retries for TLSRoute tests
  test/e2e/gateway/tlsroute_test.go
Labels: release-note/none-required

#4448 internal/provisioner: add Reconcile tests for controllers
  cmd/contour/gatewayprovisioner.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/provisioner/scheme.go
Labels: release-note/none-required

#4461 test/e2e: fix TLSRoute test flake
  test/e2e/gateway/gateway_test.go
  test/e2e/gateway/tlsroute_test.go
Labels: release-note/none-required

#4460 internal/provisioner: clean up controller logging
  internal/provisioner/controller/gateway.go
Labels: kind/cleanup, release-note/none-required

#4454 internal/provisioner: provision a ContourConfiguration resource
  changelogs/unreleased/4454-skriss-small.md
  examples/gateway-provisioner/01-roles.yaml
  examples/render/contour-gateway-provisioner.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/model/names.go
  internal/provisioner/objects/configmap/configmap.go
  internal/provisioner/objects/configmap/configmap_test.go
  internal/provisioner/objects/contourconfig/contourconfig.go
  internal/provisioner/objects/contourconfig/contourconfig_test.go
  internal/provisioner/objects/deployment/deployment.go
  internal/provisioner/rbac/rbac.go
Labels: release-note/small

#4459 internal/provisioner: support using ContourDeployment.Config
  changelogs/unreleased/4459-skriss-small.md
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/contourconfig/contourconfig.go
Labels: release-note/small

#4403 internal/envoy: Enable gzip compression for grpc-web content types.
  changelogs/unreleased/4403-bourquep-small.md
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
Labels: release-note/small

#4464 internal/envoy/v3: De-duplicate listener test content types
  internal/envoy/v3/listener_test.go
Labels: release-note/none-required

#4463 Add test and documentation to show precise hostnames override wildcards
  site/content/docs/main/config/ingress.md
  test/e2e/httpproxy/fqdn_test.go
  test/e2e/httpproxy/httpproxy_test.go
Labels: release-note/none-required

#4470 Revert back to HTTPConnectionManager XFFNumTrustedHops
  changelogs/unreleased/4470-sunjayBhatia-small.md
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/featuretests/v3/listeners_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
Labels: release-note/small

#4474 update default controller name to projectcontour.io/gateway-controller
  changelogs/unreleased/4474-skriss-small.md
  cmd/contour/gatewayprovisioner.go
  design/automated-provisioning-design.md
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/controller/gatewayclass_test.go
  test/e2e/provisioner/provisioner_test.go
  test/scripts/run-gateway-conformance.sh
Labels: release-note/small

#4469 cmd/contour & internal/contourconfig: little refactor
  cmd/contour/servecontext.go
  internal/contourconfig/contourconfiguration.go
Labels: release-note/none-required

#4475 Use non-deprecated Content-Type field in compressor filter
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
Labels: release-note/none-required

#4481 internal/envoy/v3: Merge issue in listener_test
  internal/envoy/v3/listener_test.go
Labels: release-note/none-required

#4467 define ContourDeployment v1alpha1 spec
  apis/projectcontour/v1alpha1/contourdeployment.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/contourconfig/contourconfig.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/none-required

#4482 internal/dag: use RefNotPermitted reason when applicable
  changelogs/unreleased/4482-skriss-small.md
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
Labels: release-note/small

#4424 Add grpc_stats filter to listener
  changelogs/unreleased/4424-rajatvig-small.md
  cmd/contour/servecontext_test.go
  examples/contour/01-contour-config.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  pkg/config/accesslog.go
  pkg/config/parameters_test.go
Labels: release-note/small

#4485 Another merge conflict in listener test
  internal/envoy/v3/listener_test.go
Labels: release-note/none-required

#4472 implement ContourDeployment spec
  apis/projectcontour/v1alpha1/contourdeployment.go
  changelogs/unreleased/4472-skriss-minor.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/controller/gatewayclass.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/provisioner/equality/equality_test.go
  internal/provisioner/model/model.go
  internal/provisioner/model/names.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  internal/provisioner/objects/deployment/deployment.go
  internal/provisioner/objects/service/service.go
  site/content/docs/main/config/api-reference.html
  test/e2e/provisioner/provisioner_test.go
Labels: release-note/minor

#4483 remove all ContourDeployment CRD kubebuilder defaults
  apis/projectcontour/v1alpha1/contourdeployment.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/none-required

#4466 example-workload/gatewayapi: Add a example to show howto do blue-green deployment
  changelogs/unreleased/4466-izturn-small.md
  examples/README.md
  examples/example-workload/gatewayapi/README.md
  examples/example-workload/gatewayapi/blue-green/blue-green.yaml
Labels: release-note/small

#4487 internal/envoy: use typed config for all extensions
  changelogs/unreleased/4487-skriss-small.md
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/stats.go
  internal/envoy/v3/stats_test.go
Labels: release-note/small

#4488 update to Envoy 1.22.0
  Makefile
  changelogs/unreleased/4488-skriss-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/small

#4495 fix DisableMergeSlashes propagation, add tests
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  test/e2e/httpproxy/httpproxy_test.go
  test/e2e/httpproxy/merge_slash_test.go
Labels: release-note/none-required

#4500 Image tag changes for v1.21.0-rc.1
  cmd/contour/gatewayprovisioner.go
  examples/contour/02-job-certgen.yaml
  examples/contour/03-contour.yaml
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/gateway-provisioner/03-gateway-provisioner.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#4502 CI: Use specific prefix for image file name to find sha/tag
  .github/workflows/prbuild.yaml
Labels: release-note/none-required

#4503 CI: Use specific prefix for image file name to find sha/tag
  .github/workflows/prbuild.yaml
Labels: release-note/none-required

#4486 cmd/contour: Add support for json log formatter
  changelogs/unreleased/4486-tsaarni-small.md
  cmd/contour/contour.go
  site/content/docs/main/configuration.md
Labels: release-note/small
