Repository projectcontour/contour, pull requests merged in 2022-09, with the labels that each got.

#4701 update Gateway API webhook manifest
  examples/gateway/01-admission_webhook.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
Labels: release-note/none-required

#4677 gateway provisioner: support changing Kubernetes client log level
  apis/projectcontour/v1alpha1/contourdeployment.go
  changelogs/unreleased/4677-izturn-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/deployment/deployment.go
  internal/provisioner/objects/deployment/deployment_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small

#4700 apis/projectcontour: add gvr for contourdeployments
  apis/projectcontour/v1alpha1/register.go
Labels: release-note/none-required

#4676 gateway provisioner: support changing Contour log level
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/contourconfig_helpers.go
  apis/projectcontour/v1alpha1/contourdeployment.go
  changelogs/unreleased/4676-izturn-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/deployment/deployment.go
  internal/provisioner/objects/deployment/deployment_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small

#4702 internal/provisioner: drop New func for creating a model
  internal/provisioner/model/model.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  internal/provisioner/objects/deployment/deployment_test.go
  internal/provisioner/objects/rbac/clusterrole/cluster_role_test.go
  internal/provisioner/objects/rbac/clusterrolebinding/cluster_role_binding_test.go
  internal/provisioner/objects/rbac/role/role_test.go
  internal/provisioner/objects/rbac/rolebinding/role_binding_test.go
  internal/provisioner/objects/service/service_test.go
Labels: release-note/none-required

#4703 v1.22.1 docs updates
  changelogs/CHANGELOG-v1.22.1.md
  changelogs/unreleased/4660-sunjayBhatia-small.md
  changelogs/unreleased/4690-tsaarni-small.md
  changelogs/unreleased/4691-skriss-small.md
  site/config.yaml
  site/content/docs/v1.22.1/_index.md
  site/content/docs/v1.22.1/architecture.md
  site/content/docs/v1.22.1/config/access-logging.md
  site/content/docs/v1.22.1/config/annotations.md
  site/content/docs/v1.22.1/config/api-reference.html
  site/content/docs/v1.22.1/config/api.md
  site/content/docs/v1.22.1/config/client-authorization.md
  site/content/docs/v1.22.1/config/cookie-rewriting.md
  site/content/docs/v1.22.1/config/cors.md
  site/content/docs/v1.22.1/config/external-service-routing.md
  site/content/docs/v1.22.1/config/fundamentals.md
  site/content/docs/v1.22.1/config/health-checks.md
  site/content/docs/v1.22.1/config/inclusion-delegation.md
  site/content/docs/v1.22.1/config/ingress.md
  site/content/docs/v1.22.1/config/rate-limiting.md
  site/content/docs/v1.22.1/config/request-rewriting.md
  site/content/docs/v1.22.1/config/request-routing.md
  site/content/docs/v1.22.1/config/tls-delegation.md
  site/content/docs/v1.22.1/config/tls-termination.md
  site/content/docs/v1.22.1/config/upstream-tls.md
  site/content/docs/v1.22.1/config/virtual-hosts.md
  site/content/docs/v1.22.1/config/websockets.md
  site/content/docs/v1.22.1/configuration.md
  site/content/docs/v1.22.1/deploy-options.md
  site/content/docs/v1.22.1/github.md
  site/content/docs/v1.22.1/grpc-tls-howto.md
  site/content/docs/v1.22.1/img/archoverview.png
  site/content/docs/v1.22.1/img/contour_deployment_in_k8s.png
  site/content/docs/v1.22.1/img/shutdownmanager.png
  site/content/docs/v1.22.1/img/source/shutdownmanager.drawio
  site/content/docs/v1.22.1/redeploy-envoy.md
  site/content/docs/v1.22.1/start-contributing.md
  site/content/docs/v1.22.1/troubleshooting.md
  site/content/docs/v1.22.1/troubleshooting/contour-debug-log.md
  site/content/docs/v1.22.1/troubleshooting/contour-graph.md
  site/content/docs/v1.22.1/troubleshooting/contour-xds-resources.md
  site/content/docs/v1.22.1/troubleshooting/envoy-admin-interface.md
  site/content/docs/v1.22.1/troubleshooting/envoy-debug-log.md
  site/content/docs/v1.22.1/troubleshooting/operator.md
  site/content/docs/v1.22.1/troubleshooting/profiling-contour.md
  site/content/resources/compatibility-matrix.md
  site/content/resources/upgrading.md
  site/data/docs/toc-mapping.yml
  site/data/docs/v1-22-1-toc.yml
  versions.yaml
Labels: release-note/none-required

#4706 internal/provisioner: drop kubebuilder annotations from internal Model
  internal/provisioner/model/model.go
Labels: release-note/none-required

#4708 Add flake attempts for grpc test
  test/e2e/httpproxy/grpc_test.go
Labels: release-note/none-required

#4720 Update Gateway YAML generation for extracted namespace file
  Makefile
  examples/gateway/00-namespace.yaml
  examples/gateway/01-admission_webhook.yaml
  examples/gateway/02-certificate_config.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  hack/generate-gateway-deployment.sh
  hack/generate-provisioner-deployment.sh
  test/scripts/make-kind-cluster.sh
Labels: release-note/none-required

#4722 hack/release: exclude yages repo from label sync
  .github/workflows/sync-labels.yaml
  hack/release/sync-repo-labels.sh
Labels: release-note/none-required

#4710 CORSPolicy AllowOrigin can be configured as a regex
  apis/projectcontour/v1/httpproxy.go
  changelogs/unreleased/4710-sunjayBhatia-minor.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/dag/httpproxy_processor_test.go
  internal/dag/status_test.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  internal/featuretests/v3/corspolicy_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/cors.md
Labels: release-note/minor

#4597 Added support for overload manager
  changelogs/unreleased/4597-tsaarni-major.md
  cmd/contour/bootstrap.go
  internal/envoy/bootstrap.go
  internal/envoy/v3/bootstrap.go
  internal/envoy/v3/bootstrap_test.go
  site/content/docs/main/config/overload-manager.md
  site/content/docs/main/configuration.md
  site/data/docs/main-toc.yml
Labels: release-note/major

#4711 design: add JWT verification design doc
  design/jwt-verification-design.md
Labels: kind/design, release-note/none-required

#4734 Update Gateway CRDs for latest release-0.5 cherry-picks
  examples/gateway/00-crds.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
Labels: release-note/none-required

#4725 Add guide on configuring gRPC routes
  changelogs/unreleased/4725-sunjayBhatia-docs.md
  site/content/guides/grpc.md
Labels: release-note/docs

#4735 Set grpc fixture imagepullpolicy to ifnotpresent
  test/e2e/fixtures.go
Labels: release-note/none-required

#4723 JWT verification
  apis/projectcontour/v1/detailedconditions.go
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  changelogs/unreleased/4723-skriss-major.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/accessors.go
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
  internal/envoy/cluster.go
  internal/envoy/v3/cluster.go
  internal/envoy/v3/cluster_test.go
  internal/envoy/v3/endpoint.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/route.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/jwtverification_test.go
  internal/xdscache/v3/cluster.go
  internal/xdscache/v3/listener.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/jwt-verification.md
  site/data/docs/main-toc.yml
Labels: release-note/major

#4743 test/e2e/httpproxy: Retry gRPC calls on Unimplemented status
  test/e2e/httpproxy/grpc_test.go
Labels: release-note/none-required

#4742 Fix incorrect getting started link
  site/content/docs/main/deploy-options.md
  site/content/docs/v1.22.1/deploy-options.md
Labels: release-note/none-required

#4744 internal/contour: ignore status-only Gateway API updates
  changelogs/unreleased/4744-skriss-small.md
  internal/contour/handler.go
Labels: release-note/small

#4745 internal/k8s: check Gateway API resource status equality
  changelogs/unreleased/4745-skriss-small.md
  internal/k8s/helpers.go
Labels: release-note/small

#4747 test/e2e: pass Gateway to use to test funcs
  test/e2e/framework.go
  test/e2e/gateway/gateway_allow_type_test.go
  test/e2e/gateway/gateway_test.go
  test/e2e/gateway/header_condition_match_test.go
  test/e2e/gateway/host_rewrite_test.go
  test/e2e/gateway/invalid_backend_ref_test.go
  test/e2e/gateway/path_condition_match_test.go
  test/e2e/gateway/query_param_match_test.go
  test/e2e/gateway/request_header_modifier_test.go
  test/e2e/gateway/request_mirror_test.go
  test/e2e/gateway/request_redirect_test.go
  test/e2e/gateway/tls_gateway_test.go
  test/e2e/gateway/tls_wildcard_host_test.go
  test/e2e/gateway/tlsroute_test.go
Labels: release-note/none-required

#4748 test/scripts: upgrade metallb to v0.13.5
  test/scripts/make-kind-cluster.sh
Labels: release-note/none-required

#4751 switch to GitHub Action codecov uploader
  .github/workflows/prbuild.yaml
Labels: release-note/none-required

#4754 Sync Gateway API CRDs
  examples/gateway/00-crds.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
Labels: release-note/none-required

#4755 update to Gateway API v0.5.1
  .github/workflows/prbuild.yaml
  changelogs/unreleased/4755-skriss-small.md
  examples/gateway/00-crds.yaml
  examples/gateway/01-admission_webhook.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  go.mod
  go.sum
Labels: release-note/small

#4756 Bump kind to 0.16.0
  .github/workflows/prbuild.yaml
  hack/actions/install-kubernetes-toolchain.sh
  test/scripts/make-kind-cluster.sh
Labels: release-note/none-required

#4757 Bump k8s supported version to 1.25
  .github/workflows/prbuild.yaml
  changelogs/unreleased/4757-sunjayBhatia-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  hack/actions/install-kubernetes-toolchain.sh
  site/content/resources/compatibility-matrix.md
  test/scripts/make-kind-cluster.sh
  versions.yaml
Labels: release-note/small

#4758 Exempt issues/prs with an assigned milestone from going stale
  .github/workflows/stale.yaml
Labels: release-note/none-required

#4759 only run release note/label check on PRs to main
  .github/workflows/label_check.yaml
Labels: release-note/none-required

#4762 internal/sorter: Routes w/ query param matches are sorted based on query param name
  internal/sorter/sorter.go
  internal/sorter/sorter_test.go
Labels: release-note/none-required

#4764 Bump testify to 1.8.0
  go.mod
  go.sum
Labels: release-note/none-required

#4760 internal/provisioner: fix current & expect number of ports changed bug
  internal/provisioner/equality/equality.go
  internal/provisioner/equality/equality_test.go
Labels: release-note/none-required

#4659 internal/provisioner: Unify the ensure objects created
  internal/provisioner/objects/contourconfig/contourconfig.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/deployment/deployment.go
  internal/provisioner/objects/object.go
  internal/provisioner/objects/rbac/clusterrole/cluster_role.go
  internal/provisioner/objects/rbac/clusterrolebinding/cluster_role_binding.go
  internal/provisioner/objects/rbac/rbac.go
  internal/provisioner/objects/rbac/role/role.go
  internal/provisioner/objects/rbac/rolebinding/role_binding.go
  internal/provisioner/objects/rbac/serviceaccount/service_account.go
  internal/provisioner/objects/service/service.go
Labels: release-note/none-required

#4763 Fix Gateway API route sorting when conflicts within an HTTPProxy
  changelogs/unreleased/4763-sunjayBhatia-small.md
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/gatewayapi_processor.go
  internal/sorter/sorter.go
  internal/sorter/sorter_test.go
Labels: release-note/small
