Repository projectcontour/contour, pull requests merged in 2023-05, with the labels that each got.

#5335 test/e2e/httpproxy: Fix ip filtering tests for ipv6 clusters
  test/e2e/httpproxy/ip_filtering_test.go
Labels: release-note/none-required

#5347 update to Go 1.20.4
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/5049-sunjayBhatia-small.md
  changelogs/unreleased/5254-sunjayBhatia-small.md
  changelogs/unreleased/5347-skriss-small.md
Labels: release-note/small

#5351 fix links in v1.25.0 changelog
  changelogs/CHANGELOG-v1.25.0.md
Labels: release-note/none-required

#5305 De-dupe ExtensionService resolution code
  cmd/contour/serve.go
  internal/featuretests/v3/global_authorization_test.go
  internal/featuretests/v3/globalratelimit_test.go
  internal/featuretests/v3/tracing_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
Labels: release-note/none-required

#5364 remove label sync workflow
  .github/workflows/sync-labels.yaml
  hack/release/sync-repo-labels.sh
  site/data/github-labels.yaml
  site/themes/contour/layouts/_default/how-we-work.html
  site/themes/contour/layouts/partials/github-labels.html
Labels: release-note/none-required

#5360 Adds `critical` level for access logging
  apis/projectcontour/v1alpha1/accesslog.go
  apis/projectcontour/v1alpha1/accesslog_test.go
  apis/projectcontour/v1alpha1/contourconfig.go
  changelogs/unreleased/5360-davinci26-minor.md
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/contourconfig/contourconfiguration_test.go
  internal/envoy/v3/accesslog.go
  internal/envoy/v3/accesslog_test.go
  pkg/config/parameters.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
Labels: release-note/minor

#5156 internal/dag: simplify ut for dag/status
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
Labels: lifecycle/stale, release-note/none-required

#5377 Gateway provisioner: release leader election on shutdown
  cmd/contour/gatewayprovisioner.go
Labels: release-note/none-required

#5006 metrics: Use controller-runtime metrics Registry as base
  changelogs/unreleased/5006-sunjayBhatia-small.md
  cmd/contour/serve.go
Labels: release-note/small

#5380 Update README.md
  docs/README.md
Labels: release-note/none-required

#5388 test/e2e: disable keep-alives in Poller
  test/e2e/poller.go
Labels: release-note/none-required

#5101 internal/provisioner: expose the metrics port for envoy
  changelogs/unreleased/5101-izturn-small.md
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  internal/provisioner/objects/object.go
Labels: release-note/small

#5390 internal/envoy/v3: Loosen FilterMisdirectedRequests helper
  internal/envoy/v3/listener.go
Labels: release-note/none-required

#5381 test/e2e: provisioner upgrade test
  Makefile
  test/e2e/deployment.go
  test/e2e/gateway/gateway_test.go
  test/e2e/gateway/host_rewrite_test.go
  test/e2e/gateway/multiple_gateways_and_classes_test.go
  test/e2e/gateway/multiple_https_listeners_test.go
  test/e2e/gateway/query_param_match_test.go
  test/e2e/gateway/request_header_modifier_test.go
  test/e2e/gateway/request_mirror_test.go
  test/e2e/gateway/request_redirect_test.go
  test/e2e/gateway/response_header_modifier_test.go
  test/e2e/gateway/tls_gateway_test.go
  test/e2e/gateway/tls_wildcard_host_test.go
  test/e2e/gatewayapi_predicates.go
  test/e2e/provisioner/provisioner_test.go
  test/e2e/upgrade/upgrade_test.go
  test/e2e/waiter.go
Labels: release-note/none-required

#5037 Add metrics for status update handler
  changelogs/unreleased/5037-sunjayBhatia-minor.md
  cmd/contour/serve.go
  internal/k8s/mocks/status_metrics.go
  internal/k8s/status.go
  internal/k8s/status_test.go
  internal/metrics/metrics.go
  site/content/docs/main/guides/metrics/table.md
Labels: release-note/minor

#5386 [provisioner] Add `ipFamilyPolicy` field to NetworkPublishing.
  apis/projectcontour/v1alpha1/contourdeployment.go
  changelogs/unreleased/5386-Jean-Daniel-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/controller/gatewayclass.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/provisioner/equality/equality.go
  internal/provisioner/equality/equality_test.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/service/service.go
  internal/provisioner/objects/service/service_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small

#5397 test/e2e: Additional logging in app poller
  test/e2e/poller.go
  test/e2e/upgrade/upgrade_test.go
Labels: release-note/none-required

#5398 deps: Bump go-control-plane to commit for Envoy 1.26
  go.mod
  go.sum
Labels: release-note/none-required

#5362 Bump client-go, controller-runtime and related dependencies
  cmd/contour/ingressstatus.go
  cmd/contour/serve.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  internal/contour/handler.go
  internal/contour/metrics.go
  internal/controller/controller_test.go
  internal/controller/gateway.go
  internal/controller/gatewayclass.go
  internal/controller/grpcroute.go
  internal/controller/httproute.go
  internal/controller/mocks/manager.go
  internal/controller/tlsroute.go
  internal/featuretests/v3/authorization_test.go
  internal/featuretests/v3/extensionservice_test.go
  internal/featuretests/v3/featuretests.go
  internal/featuretests/v3/global_authorization_test.go
  internal/featuretests/v3/globalratelimit_test.go
  internal/featuretests/v3/localratelimit_test.go
  internal/featuretests/v3/replaceprefix_test.go
  internal/k8s/filter.go
  internal/k8s/filter_test.go
  internal/k8s/statusaddress.go
  internal/k8s/statusaddress_test.go
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/controller/gatewayclass.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/xdscache/v3/endpointstranslator.go
  internal/xdscache/v3/endpointstranslator_test.go
  internal/xdscache/v3/server_test.go
  site/content/docs/main/config/api-reference.html
Labels: area/dependency, release-note/none-required

#5359 Design: General Global RateLimit Policy
  design/default-global-rate-limit-policy.md
Labels: kind/design, release-note/none-required

#5410 deps: bump sigs.k8s.io/controller-tools to v0.12.0
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#5416 docs: fix target port for AWS NLB TLS termination
  site/content/docs/1.23/guides/deploy-aws-tls-nlb.md
  site/content/docs/1.24/guides/deploy-aws-tls-nlb.md
  site/content/docs/1.25/guides/deploy-aws-tls-nlb.md
  site/content/docs/main/guides/deploy-aws-tls-nlb.md
Labels: release-note/none-required

#5427 cmd/contour: Failure setting GOMAXPROCS is non-fatal
  changelogs/unreleased/5427-sunjayBhatia-minor.md
  cmd/contour/contour.go
Labels: release-note/minor

#5428 release-1.25 backport: cmd/contour: Failure setting GOMAXPROCS is non-fatal (#5427)
  changelogs/unreleased/5427-sunjayBhatia-minor.md
  cmd/contour/contour.go
Labels: release-note/none-required

#5422 refactor to fix shadow-vars & dup import
  internal/featuretests/v3/extensionservice_test.go
  internal/featuretests/v3/global_authorization_test.go
  internal/featuretests/v3/jwtverification_test.go
  internal/featuretests/v3/listeners_test.go
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gatewayclass.go
  internal/xds/v3/contour.go
Labels: release-note/none-required
