Repository projectcontour/contour, pull requests merged in 2023-10, with the labels that each got.

#5678 Allow dynamic header rewrite for `host` header on HTTPProxy routes.
  apis/projectcontour/v1/httpproxy.go
  changelogs/unreleased/5678-clayton-gonsalves-minor.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  internal/envoy/route.go
  internal/envoy/v3/route.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/headerpolicy_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/request-rewriting.md
  test/e2e/httpproxy/host_header_rewrite_test.go
  test/e2e/httpproxy/httpproxy_test.go
Labels: release-note/minor

#5798 fix spelling errors
  .codespell.ignorewords
  design/configuration-crd.md
  design/downstream-crl-design.md
  design/external-authorization-design.md
  design/session-affinity.md
  internal/envoy/v3/listener.go
  site/content/docs/v1.1.0/annotations.md
  site/content/resources/faq.md
Labels: release-note/none-required

#5799 hack: bump codespell version to match GH action
  hack/codespell.sh
Labels: release-note/none-required

#5686 gateway-provisoner: add flags for enable run provisioner out of cluster
  changelogs/unreleased/5686-izturn-small.md
  cmd/contour/gatewayprovisioner.go
Labels: lifecycle/stale, release-note/small, area/gateway-provisioner

#5795 site: Bump Hugo to 0.119.0
  netlify.toml
Labels: release-note/none-required

#5804 internal/dag: default Listener ResolvedRefs to true
  changelogs/unreleased/5804-skriss-small.md
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
  test/scripts/run-gateway-conformance.sh
Labels: release-note/small

#5818 switch to github.com/distribution/reference
  cmd/contour/gatewayprovisioner.go
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#5806 deps: Bump logrusr to v4.0.0
  go.mod
  go.sum
  internal/k8s/log.go
  internal/k8s/log_test.go
  test/conformance/gatewayapi/gateway_conformance_test.go
  test/e2e/framework.go
Labels: area/dependency, release-note/none-required

#5672 wait for cache sync and DAG build before starting xDS server
  changelogs/unreleased/5672-therealak12-minor.md
  cmd/contour/serve.go
  internal/contour/handler.go
  internal/featuretests/v3/featuretests.go
  internal/xdscache/v3/server_test.go
Labels: release-note/minor

#5821 Bump Envoy to 1.27.1
  Makefile
  changelogs/unreleased/5821-sunjayBhatia-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/small

#5823 release-1.26: Bump Envoy to 1.27.1
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5824 release-1.25: Bump Envoy to 1.26.5
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5825 release-1.24: Bump Envoy to 1.25.10
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5830 release-1.26: Bump golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#5837 release-1.25: Bump grpc-go to v1.56.3
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#5839 release-1.24: Bump grpc-go to v1.56.3
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#5838 release-1.24: Bump golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#5841 Bump go to 1.21.3
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/5783-skriss-small.md
  changelogs/unreleased/5841-sunjayBhatia-small.md
Labels: area/dependency, release-note/small

#5836 release-1.25: Bump golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#5827 Add configurability for HTTP requests per IO cycle
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/5827-sunjayBhatia-minor.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/envoy/v3/runtime.go
  internal/envoy/v3/runtime_test.go
  internal/xdscache/v3/runtime.go
  internal/xdscache/v3/runtime_test.go
  internal/xdscache/v3/server_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
Labels: release-note/minor

#5814 provisioner: fix envoy-max-heapsize not set
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/dataplane/dataplane_test.go
Labels: release-note/none-required

#5850 HTTP/2 max concurrent streams can be configured
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/5850-sunjayBhatia-minor.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/contourconfig/contourconfiguration_test.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
Labels: release-note/minor

#5852 release-1.25: Backport #5827 and #5850
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/5827-sunjayBhatia-minor.md
  changelogs/unreleased/5850-sunjayBhatia-minor.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/contourconfig/contourconfiguration_test.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/runtime.go
  internal/envoy/v3/runtime_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  internal/xdscache/v3/runtime.go
  internal/xdscache/v3/runtime_test.go
  internal/xdscache/v3/server_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
Labels: release-note/none-required

#5853 release-1.24: Backport #5827 and #5850
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/5827-sunjayBhatia-minor.md
  changelogs/unreleased/5850-sunjayBhatia-minor.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/contourconfig/contourconfiguration_test.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/runtime.go
  internal/envoy/v3/runtime_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  internal/xdscache/v3/runtime.go
  internal/xdscache/v3/runtime_test.go
  internal/xdscache/v3/server_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
Labels: release-note/none-required

#5860 release-1.24: Bump Envoy to v1.25.11
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5861 release-1.25: Bump Envoy to v1.26.6
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5862 release-1.26: Bump Envoy to v1.27.2
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5863 Bump Envoy to v1.27.2
  Makefile
  changelogs/unreleased/5821-sunjayBhatia-small.md
  changelogs/unreleased/5863-sunjayBhatia-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/small

#5858 release-1.26: golangci-lint: Fix revive rules
  .golangci.yml
  cmd/contour/shutdownmanager.go
  internal/contour/handler.go
  internal/controller/gateway.go
  internal/controller/gatewayclass.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/envoy/route.go
  internal/envoy/v3/bootstrap.go
  internal/envoy/v3/listener.go
  internal/k8s/helpers.go
  internal/k8s/helpers_test.go
  internal/k8s/log.go
  internal/k8s/statusaddress.go
  internal/provisioner/objects/secret/secret.go
  internal/status/gatewayclass.go
  internal/xds/v3/contour_test.go
  internal/xdscache/snapshot.go
  internal/xdscache/v3/endpointstranslator.go
  internal/xdscache/v3/runtime.go
  test/e2e/incluster/incluster_test.go
  test/e2e/incluster/leaderelection_test.go
Labels: release-note/none-required

#5859 site: 1.26.1, 1.25.3, 1.24.6 patch releases
  changelogs/CHANGELOG-v1.24.6.md
  changelogs/CHANGELOG-v1.25.3.md
  changelogs/CHANGELOG-v1.26.1.md
  site/content/docs/1.24/configuration.md
  site/content/docs/1.25/configuration.md
  site/content/docs/1.26/configuration.md
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/none-required

#5805 test/e2e: Add race detection in e2e tests
  test/e2e/deployment.go
  test/e2e/framework.go
Labels: release-note/none-required

#5857 golangci-lint: Fix revive rules
  .golangci.yml
  cmd/contour/shutdownmanager.go
  internal/contour/handler.go
  internal/controller/gateway.go
  internal/controller/gatewayclass.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/dag/policy.go
  internal/envoy/route.go
  internal/envoy/v3/bootstrap.go
  internal/envoy/v3/listener.go
  internal/k8s/helpers.go
  internal/k8s/helpers_test.go
  internal/k8s/log.go
  internal/k8s/statusaddress.go
  internal/provisioner/objects/secret/secret.go
  internal/status/gatewayclass.go
  internal/xds/v3/contour_test.go
  internal/xdscache/snapshot.go
  internal/xdscache/v3/endpointstranslator.go
  internal/xdscache/v3/runtime.go
  test/e2e/incluster/incluster_test.go
  test/e2e/incluster/leaderelection_test.go
Labels: release-note/none-required

#5871 use Gateway API release version in versions.yaml, compat matrix
  changelogs/unreleased/5871-skriss-docs.md
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/docs

#5870 update Envoy to 1.28.0
  Makefile
  changelogs/unreleased/5863-sunjayBhatia-small.md
  changelogs/unreleased/5870-skriss-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: area/dependency, release-note/small

#5888 release-1.24: Bump mockery to fix dependabot
  go.mod
  go.sum
  internal/controller/mocks/manager.go
  internal/debug/mocks/dag_builder.go
  internal/k8s/mocks/cache.go
  internal/leadership/mocks/need_leader_election_notification.go
Labels: release-note/none-required

#5892 fix lint issue
  internal/xdscache/v3/endpointslicetranslator.go
Labels: release-note/none-required

#5893 Run Gateway API conformance and generate report on tagged builds
  .github/workflows/build_tag.yaml
  .gitignore
  test/conformance/gatewayapi/gateway_conformance_test.go
  test/scripts/run-gateway-conformance.sh
Labels: release-note/none-required

#5894 Minor fixes to Gateway API conformance on release tag
  .github/workflows/build_tag.yaml
  test/conformance/gatewayapi/gateway_conformance_test.go
Labels: release-note/none-required

#5900 v1.27.0 post-release updates
  .github/dependabot.yml
  .github/workflows/trivy-scan.yaml
  netlify.toml
Labels: release-note/none-required

#5916 test/scripts: check for gateway-system namespace
  test/scripts/install-provisioner-release.sh
Labels: release-note/none-required

#5915 remove operator references
  netlify.toml
  site/content/resources/compatibility-matrix.md
Labels: release-note/none-required
