Repository projectcontour/contour, pull requests merged in 2023-12, with the labels that each got.

#5968 implement Gateway infrastructure labels/annotations
  apis/projectcontour/v1alpha1/contourdeployment.go
  changelogs/unreleased/5968-skriss-deprecation.md
  changelogs/unreleased/5968-skriss-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/model/model.go
  internal/provisioner/model/names.go
  internal/provisioner/objects/contourconfig/contourconfig.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  internal/provisioner/objects/deployment/deployment.go
  internal/provisioner/objects/deployment/deployment_test.go
  internal/provisioner/objects/rbac/clusterrole/cluster_role.go
  internal/provisioner/objects/rbac/clusterrolebinding/cluster_role_binding.go
  internal/provisioner/objects/rbac/role/role.go
  internal/provisioner/objects/rbac/rolebinding/role_binding.go
  internal/provisioner/objects/rbac/serviceaccount/service_account.go
  internal/provisioner/objects/secret/secret.go
  internal/provisioner/objects/service/service.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small, release-note/deprecation

#5896 Use necojackarc/auto-request-review action to request reviews from non-maintainers
  .github/reviewers.yaml
  .github/workflows/request-reviews.yaml
Labels: release-note/none-required

#5997 Gateway API: support request timeout
  changelogs/unreleased/5997-izturn-minor.md
  internal/dag/builder_test.go
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
  test/conformance/gatewayapi/gateway_conformance_test.go
Labels: release-note/minor

#6009 site: Remove leaderelection from config file params
  site/content/docs/1.21/configuration.md
  site/content/docs/1.22/configuration.md
  site/content/docs/1.23/configuration.md
  site/content/docs/1.24/configuration.md
  site/content/docs/1.25/configuration.md
  site/content/docs/1.26/configuration.md
  site/content/docs/1.27/configuration.md
  site/content/docs/main/configuration.md
Labels: release-note/none-required

#5961 Gateway API: fix for failing GatewayWithAttachedRoutes conformance test
  changelogs/unreleased/5961-izturn-small.md
  internal/dag/gatewayapi_processor.go
  internal/dag/gatewayapi_processor_test.go
  internal/dag/status_test.go
  internal/gatewayapi/listeners.go
  test/conformance/gatewayapi/gateway_conformance_test.go
Labels: area/gateway-api, release-note/small

#6012 update Gateway API conformance exclusions
  test/conformance/gatewayapi/gateway_conformance_test.go
  test/scripts/run-gateway-conformance.sh
Labels: release-note/none-required

#6025 dependabot: group upload/download artifact actions bumps
  .github/dependabot.yml
Labels: release-note/none-required

#6028 release-1.25: Bump golang.org/x/crypto to 0.17.0
  go.mod
  go.sum
Labels: release-note/none-required

#6029 release-1.26: Bump golang.org/x/crypto to 0.17.0
  go.mod
  go.sum
Labels: release-note/none-required

#5828 allow configuration of upstream TLS connection settings
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/5828-KauzClay-minor.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/contourconfig/contourconfiguration.go
  internal/contourconfig/contourconfiguration_test.go
  internal/dag/dag.go
  internal/dag/extension_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/httpproxy_processor_test.go
  internal/dag/ingress_processor.go
  internal/envoy/v3/auth.go
  internal/envoy/v3/auth_test.go
  internal/envoy/v3/cluster.go
  internal/envoy/v3/cluster_test.go
  internal/envoy/v3/socket_test.go
  internal/featuretests/v3/backendcavalidation_test.go
  internal/featuretests/v3/backendclientauth_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/externalname_test.go
  internal/featuretests/v3/headerpolicy_test.go
  internal/featuretests/v3/tcpproxy_test.go
  internal/featuretests/v3/upstreamprotocol_test.go
  internal/featuretests/v3/upstreamtls_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
  test/e2e/httpproxy/backend_tls_protocol_version_test.go
  test/e2e/httpproxy/httpproxy_test.go
Labels: release-note/minor

#6031 update Kubernetes support for 1.29
  .github/workflows/prbuild.yaml
  changelogs/unreleased/6031-skriss-small.md
  hack/actions/install-kubernetes-toolchain.sh
  site/content/resources/compatibility-matrix.md
  test/scripts/make-kind-cluster.sh
  versions.yaml
Labels: release-note/small

#6032 remove disabled ingress-conformance run from CI
  .github/workflows/prbuild.yaml
  hack/actions/install-kubernetes-toolchain.sh
Labels: release-note/none-required

#6033 Promote upstream TLS changelog entry from minor to major
  changelogs/unreleased/5828-KauzClay-major.md
  changelogs/unreleased/5828-KauzClay-minor.md
Labels: release-note/none-required
