Repository projectcontour/contour, pull requests merged in 2023-04, with the labels that each got.

#5238 docs: updated contributing instructions
  CONTRIBUTING.md
  hack/codespell.sh
  test/scripts/install-contour-working.sh
  test/scripts/install-provisioner-working.sh
  test/scripts/kind-expose-port.yaml
Labels: release-note/none-required

#5250 main: Bump Envoy to 1.25.4
  Makefile
  changelogs/unreleased/5250-sunjayBhatia-minor.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/minor

#5254 Bump go to 1.20.3
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/5218-sunjayBhatia-small.md
  changelogs/unreleased/5254-sunjayBhatia-small.md
Labels: release-note/small

#5251 release-1.24: Bump Envoy to 1.25.4 and go to 1.19.8
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5253 release-1.22: Bump Envoy to 1.23.7 and go to 1.19.8
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5255 Changelogs and site updates for patch releases
  changelogs/CHANGELOG-v1.22.6.md
  changelogs/CHANGELOG-v1.23.5.md
  changelogs/CHANGELOG-v1.24.3.md
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/none-required

#5233 internal/provisioner: Do not use hard-coded values, but configuration defined ports.
  changelogs/unreleased/5233-Jean-Daniel-small.md
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
Labels: release-note/small

#5259 internal/dag: Always set resolved refs in GW API processor
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
Labels: release-note/none-required

#5194 Bump gateway-api to v0.6.2
  changelogs/unreleased/5063-sunjayBhatia-small.md
  changelogs/unreleased/5194-sunjayBhatia-small.md
  examples/gateway/00-crds.yaml
  examples/gateway/01-admission_webhook.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  go.mod
  go.sum
  hack/generate-gateway-yaml.sh
Labels: release-note/small

#5260 internal/dag: set condition for HTTP vhost with ExtAuth configured
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
Labels: release-note/none-required

#5270 minor reorganization for CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release-note/none-required

#5239 Gateway API: support regex path and header match
  changelogs/unreleased/5239-fangfpeng-small.md
  internal/dag/builder_test.go
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
  internal/gatewayapi/helpers.go
Labels: release-note/small

#5272 fix: nil pointer on global extauth when `authPolicy.context` not configured.
  cmd/contour/serve.go
Labels: release-note/none-required

#5043 Add tracing support
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/contourconfig_helpers.go
  apis/projectcontour/v1alpha1/contourconfig_helpers_test.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/5043-yangyy93-major.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  examples/tracing/01-opentelemetry-collector.yaml
  examples/tracing/02-opentelemetry-extsvc.yaml
  examples/tracing/03-contour-config.yaml
  internal/envoy/v3/listener.go
  internal/envoy/v3/tracing.go
  internal/envoy/v3/tracing_test.go
  internal/featuretests/v3/tracing_test.go
  internal/xdscache/v3/listener.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/tracing.md
  site/data/docs/main-toc.yml
Labels: release-note/major

#5157 internal/dag: configure 502 if include references another (#5016)
  changelogs/unreleased/5157-liangyuanpeng-small.md
  internal/dag/builder_test.go
  internal/dag/httpproxy_processor.go
Labels: release-note/small

#5278 hack: change back to random image tag
  test/scripts/install-contour-working.sh
  test/scripts/install-provisioner-working.sh
Labels: release-note/none-required

#5301 chore: remove double package import
  internal/envoy/v3/listener.go
Labels: release-note/none-required

#5304 Upgrading metallb to v0.13.9
  test/scripts/make-kind-cluster.sh
Labels: release-note/none-required

#5303 internal/envoy/v3: adds a testcase for slow start mode with non-default LB policy
  internal/envoy/v3/cluster_test.go
Labels: release-note/none-required

#5279 Move more "to pointer" helpers to generic ref.To
  cmd/contour/servecontext_test.go
  internal/contourconfig/contourconfiguration.go
  internal/contourconfig/contourconfiguration_test.go
  internal/provisioner/intstr/intstr.go
  internal/provisioner/model/model.go
  test/e2e/fixtures.go
  test/e2e/httpproxy/external_name_test.go
  test/e2e/httpproxy/fqdn_test.go
  test/e2e/incluster/rbac_test.go
  test/e2e/ingress/backend_tls_test.go
  test/e2e/ingress/headers_policy_test.go
  test/e2e/ingress/ingress_class_test.go
  test/e2e/ingress/long_path_match_test.go
  test/e2e/ingress/tls_wildcard_host_test.go
Labels: release-note/none-required

#5008 httpproxy: Add support for ip-based filtering
  apis/projectcontour/v1/detailedconditions.go
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  changelogs/unreleased/5008-ecordell-major.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/dag/httpproxy_processor_test.go
  internal/dag/status_test.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  internal/featuretests/v3/ipfilter_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/ip-filtering.md
  site/data/docs/main-toc.yml
  test/e2e/httpproxy/httpproxy_test.go
  test/e2e/httpproxy/ip_filtering_test.go
Labels: release-note/major

#5257 Make alpha Gateway APIs optional
  changelogs/unreleased/5080-nsimons-minor.md
  cmd/contour/serve.go
  examples/optional-features/kustomization.yaml
  examples/render/kustomization.yaml
  site/content/docs/main/configuration.md
  site/content/docs/main/deploy-options.md
Labels: release-note/none-required

#5296 internal/dag: Fix for duplicate include detection
  changelogs/unreleased/5296-sunjayBhatia-small.md
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
Labels: release-note/small

#5307 chore: extend tracing test for custom tags
  internal/featuretests/v3/tracing_test.go
Labels: release-note/none-required

#5000 internal/dag: Add exact path match condition in HttpProxy
  apis/projectcontour/v1/httpproxy.go
  changelogs/unreleased/5000-arjunsalyan-minor.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/builder_test.go
  internal/dag/conditions.go
  internal/dag/conditions_test.go
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
  internal/fixture/service_fixtures.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/inclusion-delegation.md
  site/content/docs/main/config/request-routing.md
  test/e2e/httpproxy/exact_path_condition_match_test.go
  test/e2e/httpproxy/httpproxy_test.go
  test/e2e/httpproxy/include_exact_condition_test.go
Labels: release-note/minor

#5320 update to Envoy v1.26.1
  Makefile
  changelogs/unreleased/5320-skriss-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/small

#5322 [release-1.24] update Envoy to v1.25.6
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5323 test/e2e/incluster: Add memory usage test for header includes
  test/e2e/incluster/incluster_test.go
  test/e2e/incluster/memory_usage_test.go
Labels: release-note/none-required

#5324 add make install-provisioner-release
  Makefile
  test/scripts/install-provisioner-release.sh
Labels: release-note/none-required

#5297 [release-1.24] internal/dag: Fix bug in duplicate include match detection that caused memory usage spike
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
  test/e2e/incluster/incluster_test.go
  test/e2e/incluster/memory_usage_test.go
Labels: release-note/none-required

#5099 Reduce the memory footprint by optimizing Kubernetes informer cache
  changelogs/unreleased/5099-tsaarni-small.md
  cmd/contour/serve.go
Labels: release-note/small

#5310 support query param regex matching in Gateway API
  changelogs/unreleased/5310-padlar-small.md
  internal/dag/builder_test.go
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
Labels: release-note/small

#5327 minor RC process updates
  site/content/resources/release-process.md
Labels: release-note/none-required

#5329 1.24.4 website updates
  changelogs/CHANGELOG-v1.24.4.md
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/none-required
