Repository projectcontour/contour, pull requests merged in 2023-08, with the labels that each got.

#5656 Updated code of conduct
  CODE_OF_CONDUCT.md
Labels: release-note/none-required

#5530 internal/dag: simplify ut for dag/secret
  internal/dag/secret_test.go
Labels: area/testing, release-note/none-required

#5532 internal/dag: simplify ut for dag
  internal/dag/accessors_test.go
  internal/dag/builder_test.go
  internal/dag/cache_test.go
  internal/dag/dag_test.go
  internal/dag/status_test.go
Labels: area/testing, release-note/none-required

#5663 Bump golang to 1.20.7
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/5555-skriss-small.md
  changelogs/unreleased/5663-sunjayBhatia-small.md
Labels: release-note/small

#5665 release-1.24: Bump go to 1.19.12
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
Labels: release-note/none-required

#5664 release-1.25: Bump go to 1.20.7
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
Labels: release-note/none-required

#5533 make the maximum TLS version is configurable
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/contourconfig_helpers.go
  apis/projectcontour/v1alpha1/contourconfig_helpers_test.go
  changelogs/unreleased/5533-izturn-small.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/annotation/annotations.go
  internal/contourconfig/contourconfiguration.go
  internal/contourconfig/contourconfiguration_test.go
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/dag/status_test.go
  internal/envoy/v3/auth.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/socket_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/listeners_test.go
  internal/featuretests/v3/tlsprotocolversion_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/annotations.md
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
Labels: area/tls, release-note/small

#5652 gw-api: Support multiple RequestMirror filters per rule in GW API
  changelogs/unreleased/5652-LiorLieberman-minor.md
  internal/dag/accessors.go
  internal/dag/accessors_test.go
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
  internal/debug/dot.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
Labels: release-note/minor

#5651 Fix Gateway Status Addresses Updater with multiple Ingress entries.
  changelogs/unreleased/5651-Jean-Daniel-small.md
  internal/k8s/statusaddress.go
  internal/k8s/statusaddress_test.go
Labels: release-note/small

#5683 fix links in security process doc
  site/content/resources/security-checklist.md
  site/content/resources/security-process.md
Labels: release-note/none-required

#5696 deps: downgrade github.com/chigopher/pathlib to v0.15.0
  go.mod
  go.sum
Labels: release-note/none-required

#5684 Migrate to new Mockery config
  .mockery.yaml
  Makefile
  internal/controller/controller_test.go
  internal/debug/dot_test.go
  internal/k8s/status_test.go
  internal/k8s/statusaddress_test.go
  internal/leadership/notifier_test.go
Labels: release-note/none-required

#5700 update to Kubernetes 1.28
  .github/workflows/prbuild.yaml
  changelogs/unreleased/5700-skriss-small.md
  go.mod
  go.sum
  hack/actions/install-kubernetes-toolchain.sh
  site/content/resources/compatibility-matrix.md
  test/scripts/make-kind-cluster.sh
  versions.yaml
Labels: release-note/small

#5701 deps: bump sigs.k8s.io/kustomize/kyaml to v0.14.3
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#5670 add more information in Error Message of httpproxy
  changelogs/unreleased/5670-HeavenTonight-small.md
  internal/dag/httpproxy_processor.go
  internal/dag/status_test.go
Labels: release-note/small

#5704 Run dependabot scans on Sundays
  .github/dependabot.yml
Labels: release-note/none-required

#5568 Bump Gateway API to v0.8.0-rc2
  changelogs/unreleased/5353-sunjayBhatia-minor.md
  changelogs/unreleased/5568-sunjayBhatia-minor.md
  examples/gateway/00-crds.yaml
  examples/gateway/00-namespace.yaml
  examples/gateway/01-admission_webhook.yaml
  examples/gateway/02-certificate_config.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  go.mod
  go.sum
  internal/dag/gatewayapi_processor.go
  internal/k8s/statusaddress.go
  internal/k8s/statusaddress_test.go
  test/e2e/gateway/request_redirect_test.go
  test/scripts/run-gateway-conformance.sh
Labels: release-note/minor

#5725 update contour-authserver to v4, use GHCR
  changelogs/unreleased/5725-skriss-small.md
  examples/global-external-auth/01-authserver.yaml
  site/content/docs/main/guides/external-authorization.md
  site/content/examples/authdemo/02-auth-deployment.yaml
  test/e2e/httpproxy/external_auth_test.go
Labels: release-note/small

#5433 docs: add Gateway API documentation
  site/content/docs/main/config/gateway-api.md
  site/content/docs/main/guides/gateway-api.md
  site/content/getting-started/_index.md
  site/data/docs/main-toc.yml
Labels: release-note/none-required

#5726 Bump Gateway API to v0.8.0
  changelogs/unreleased/5726-sunjayBhatia-minor.md
  examples/gateway/00-crds.yaml
  examples/gateway/01-admission_webhook.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  go.mod
  go.sum
Labels: release-note/minor

#5731 update to Go 1.21.0
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/5731-skriss-small.md
Labels: release-note/small
