Repository projectcontour/contour, pull requests merged in 2023-11, with the labels that each got.

#5898 update to Gateway API 1.0
  changelogs/unreleased/5898-skriss-major.md
  examples/gateway/00-crds.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  go.mod
  go.sum
  internal/controller/gateway.go
  internal/dag/builder_test.go
  internal/dag/gatewayapi_processor.go
  internal/dag/gatewayapi_processor_test.go
  internal/dag/policy.go
  internal/dag/status_test.go
  internal/featuretests/v3/httproute_test.go
  internal/featuretests/v3/listeners_test.go
  internal/featuretests/v3/routesourcemetadata_test.go
  internal/featuretests/v3/routeweight_test.go
  internal/featuretests/v3/tcproute_test.go
  internal/featuretests/v3/tlsroute_test.go
  internal/gatewayapi/helpers.go
  internal/gatewayapi/listeners.go
  internal/gatewayapi/listeners_test.go
  internal/k8s/statusaddress.go
  internal/k8s/statusaddress_test.go
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/controller/gatewayclass.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/status/gatewayclassconditions.go
  internal/status/gatewayclassconditions_test.go
  internal/status/gatewaystatus_test.go
  test/conformance/gatewayapi/gateway_conformance_test.go
  test/e2e/gateway/gateway_test.go
  test/e2e/gateway/host_rewrite_test.go
  test/e2e/gateway/multiple_gateways_and_classes_test.go
  test/e2e/gateway/multiple_https_listeners_test.go
  test/e2e/gateway/request_header_modifier_test.go
  test/e2e/gateway/request_redirect_test.go
  test/e2e/gateway/response_header_modifier_test.go
  test/e2e/gateway/tls_gateway_test.go
  test/e2e/gateway/tls_wildcard_host_test.go
  test/e2e/gatewayapi_predicates.go
  test/e2e/provisioner/provisioner_test.go
  test/e2e/upgrade/upgrade_test.go
Labels: release-note/major

#5931 release instructions: Add guidance on submitting gw api conformance report
  site/content/resources/release-process.md
Labels: kind/cleanup, release-note/none-required

#5933 test/e2e: add flake retries for HTTPS metrics test
  test/e2e/infra/metrics_test.go
Labels: release-note/none-required

#5928 test/e2e: NamespacedTest helper can create/delete multiple namespaces
  test/e2e/framework.go
Labels: release-note/none-required

#5864 internal/envoy: fix wrong check for filter/router
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
Labels: kind/bug, area/infra, release-note/none-required

#5537 Add ecosystem page
  site/content/resources/adopters.md
  site/content/resources/ecosystem.md
  site/data/docs/main-toc.yml
  site/img/adopters/VMware-logo-grey.jpg
  site/themes/contour/static/img/adopters/daocloud.png
  site/themes/contour/static/img/adopters/flyte.png
  site/themes/contour/static/img/adopters/gojek.svg
  site/themes/contour/static/img/adopters/knative.svg
Labels: kind/feature, area/website, release-note/none-required

#5941 bump golangci-lint to v1.55.2 and fix new lint issues
  .github/workflows/prbuild.yaml
  .golangci.yml
  hack/golangci-lint
  internal/dag/policy_test.go
  internal/envoy/v3/bootstrap_test.go
  internal/envoy/v3/listener.go
  internal/featuretests/kubernetes.go
  internal/fixture/certificate_constants.go
  internal/xdscache/v3/endpointslicetranslator_test.go
  internal/xdscache/v3/endpointstranslator_test.go
  internal/xdscache/v3/secret_test.go
Labels: area/tooling, release-note/none-required

#5959 Use Info instead of Printf logs for dag build info lines
  cmd/contour/serve.go
Labels: release-note/none-required

#5960 Add more options on how to resolve stale PRs
  .github/workflows/stale.yaml
Labels: release-note/none-required

#5965 release-1.26: Bump golang.org/x/image to get rid of Trivy scan results
  go.mod
  go.sum
Labels: release-note/none-required

#5964 release-1.25: Bump golang.org/x/image to get rid of Trivy scan results
  go.mod
  go.sum
Labels: release-note/none-required

#5963 Use setup-go action before codeql
  .github/workflows/codeql-analysis.yml
Labels: release-note/none-required

#5934 Gateway API: support backend appProtocol
  changelogs/unreleased/5934-izturn-minor.md
  internal/dag/accessors.go
  internal/dag/accessors_test.go
  internal/dag/builder_test.go
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
  test/conformance/gatewayapi/gateway_conformance_test.go
Labels: area/gateway-api, release-note/minor

#5840 httpproxy: fix the order for filter: AuthZ & AuthN
  changelogs/unreleased/5840-izturn-minor.md
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  internal/xdscache/v3/secret_test.go
Labels: kind/bug, area/httpproxy, release-note/minor

#5971 switch from golang.org/x/exp/slices to slices pkg
  apis/projectcontour/v1alpha1/contourconfig_helpers.go
  go.mod
Labels: release-note/none-required

#5972 fix go-control-plane instantiation order
  changelogs/unreleased/5972-skriss-small.md
  cmd/contour/serve.go
  internal/xds/v3/hash.go
  internal/xds/v3/snapshotter.go
  internal/xdscache/v3/snapshot.go
Labels: release-note/small

#5973 cmd/contour: only create snapshot handler for envoy xDS server
  cmd/contour/serve.go
Labels: release-note/none-required

#5975 test/e2e: replace fixed sleeps with require.Eventually
  test/e2e/infra/endpointslice_test.go
Labels: release-note/none-required

#5986 release-1.25: test/e2e: add flake retries for HTTPS metrics test
  test/e2e/infra/metrics_test.go
Labels: kind/flake, release-note/none-required

#5984 release-1.27: test/e2e: add flake retries for HTTPS metrics test
  test/e2e/infra/metrics_test.go
Labels: kind/flake, release-note/none-required
