Repository projectcontour/contour, pull requests merged in 2023-06, with the labels that each got.

#5214 Allow limiting Contour to watch certain namespaces
  Makefile
  changelogs/unreleased/5214-nsimons-minor.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  examples/namespaced/kustomization.yaml
  site/content/docs/main/config/inclusion-delegation.md
  site/content/docs/main/config/tls-delegation.md
  site/content/docs/main/config/virtual-hosts.md
  site/content/docs/main/configuration.md
  site/content/docs/main/deploy-options.md
  test/e2e/framework.go
  test/e2e/httpproxy/httpproxy_test.go
  test/e2e/httpproxy/namespaces_test.go
  test/e2e/httpproxy/root_namespaces_test.go
Labels: release-note/minor

#5429 golangci-lint: use go run locally, tidy config file
  .github/workflows/prbuild.yaml
  .golangci.yml
  hack/golangci-lint
Labels: release-note/none-required

#5430 internal/provisioner: simplify ut for provisioner/controller
  internal/provisioner/controller/gateway_test.go
Labels: release-note/none-required, area/gateway-provisioner

#5431 docs: remove Operator references
  CONTRIBUTING.md
  site/content/docs/main/deploy-options.md
  site/content/docs/main/troubleshooting.md
  site/content/docs/main/troubleshooting/operator.md
Labels: release-note/none-required

#5346 crd/ContourDeployment: Add field 'podAnnotations' for contour
  apis/projectcontour/v1alpha1/contourdeployment.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/5346-izturn-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  internal/provisioner/objects/deployment/deployment.go
  internal/provisioner/objects/deployment/deployment_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small

#5436 test/e2e: Delete dependent objects in background
  test/e2e/deployment.go
Labels: release-note/none-required

#5423 rename interface{} to any
  .golangci.yml
  apis/projectcontour/v1/helpers.go
  cmd/contour/serve.go
  internal/annotation/annotations_test.go
  internal/contour/handler.go
  internal/contour/metrics.go
  internal/contour/metrics_test.go
  internal/dag/builder_test.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/dag/gatewayapi_processor.go
  internal/dag/status.go
  internal/dag/status_test.go
  internal/debug/dot.go
  internal/featuretests/v3/featuretests.go
  internal/fixture/detailedcondition.go
  internal/k8s/filter.go
  internal/k8s/filter_test.go
  internal/k8s/helpers.go
  internal/k8s/kind.go
  internal/k8s/kind_test.go
  internal/k8s/statusaddress.go
  internal/k8s/statuscache.go
  internal/protobuf/helpers.go
  internal/protobuf/testhelpers.go
  internal/sorter/sorter.go
  internal/xdscache/snapshot.go
  internal/xdscache/v3/cluster_test.go
  internal/xdscache/v3/endpointstranslator.go
  internal/xdscache/v3/listener_test.go
  internal/xdscache/v3/route_test.go
  internal/xdscache/v3/secret_test.go
  test/e2e/deployment.go
  test/e2e/httpproxy/required_field_validation_test.go
  test/e2e/provisioner.go
Labels: area/infra, release-note/none-required

#5437 internal/envoy/v3: RouteConfiguration ignores port when choosing virtualhost
  changelogs/unreleased/5437-sunjayBhatia-minor.md
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/ingress_processor.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  internal/featuretests/v3/wildcardhost_test.go
Labels: release-note/minor

#5353 Bump Gateway API to v0.7.1
  changelogs/unreleased/5353-sunjayBhatia-minor.md
  examples/gateway/00-crds.yaml
  examples/gateway/01-admission_webhook.yaml
  examples/gateway/02-certificate_config.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  go.mod
  go.sum
  internal/dag/builder_test.go
  internal/dag/gatewayapi_processor.go
  internal/gatewayapi/helpers.go
  test/conformance/gatewayapi/gateway_conformance_test.go
  test/e2e/framework.go
  test/scripts/run-gateway-conformance.sh
Labels: release-note/minor

#5449 Bump Envoy to v1.26.2
  Makefile
  changelogs/unreleased/5449-sunjayBhatia-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/small

#5451 release-1.24: Bump Envoy to v1.25.7
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5452 release-1.23: Bump Envoy to v1.24.8
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5456 release-1.25: Bump docker/distribution due to CVE scan
  go.mod
  go.sum
Labels: release-note/none-required

#5455 release-1.24: Bump docker/distribution due to CVE scan
  go.mod
  go.sum
Labels: release-note/none-required

#5454 release-1.23: Bump docker/distribution due to CVE scan
  go.mod
  go.sum
Labels: release-note/none-required

#5457 Wait for gateway-api admission server to roll out in install script
  test/scripts/install-provisioner-release.sh
Labels: kind/flake, release-note/none-required

#5448 test/e2e/gateway: Remove request mirror test
  test/e2e/gateway/gateway_test.go
  test/e2e/gateway/request_mirror_test.go
Labels: release-note/none-required

#5160 support many Gateway Listeners
  apis/projectcontour/v1/detailedconditions.go
  changelogs/unreleased/5160-skriss-major.md
  cmd/contour/shutdownmanager.go
  cmd/contour/shutdownmanager_test.go
  internal/dag/accessors.go
  internal/dag/accessors_test.go
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/dag/listener_processor.go
  internal/dag/status_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/httproute_test.go
  internal/featuretests/v3/routeweight_test.go
  internal/featuretests/v3/tlsroute_test.go
  internal/gatewayapi/listeners.go
  internal/gatewayapi/listeners_test.go
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  test/conformance/gatewayapi/gateway_conformance_test.go
Labels: release-note/major

#5434 internal/sorter: Routes with method matching get precedence
  changelogs/unreleased/5434-sunjayBhatia-minor.md
  internal/sorter/sorter.go
  internal/sorter/sorter_test.go
Labels: release-note/minor

#5425 internal/provisioner: set the default resource requirements for containers: shutdown-manager & envoy-initconfig
  changelogs/unreleased/5425-izturn-small.md
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
Labels: release-note/small, area/gateway-provisioner

#5473 test/e2e: Debugging fixes
  test/e2e/deployment.go
  test/e2e/gateway/query_param_match_test.go
  test/e2e/gateway/tls_gateway_test.go
  test/e2e/http.go
Labels: release-note/none-required

#5472 internal/dag: GetServiceClusters no longer returns ExternalName clusters
  internal/dag/accessors.go
  internal/dag/accessors_test.go
Labels: release-note/none-required

#5475 Extend gateway api conformance test timeout
  test/scripts/run-gateway-conformance.sh
Labels: release-note/none-required

#5477 fix new codespell issues
  changelogs/CHANGELOG-v1.20.0.md
  site/content/posts/2020-01-16-announcing-contour-1.1.md
Labels: release-note/none-required

#5478 test/e2e: extract generic helper for creating/waiting
  test/e2e/framework.go
Labels: release-note/none-required

#5471 Gateway API: add support for TCPRoute
  changelogs/unreleased/5471-skriss-minor.md
  cmd/contour/serve.go
  examples/contour/02-role-contour.yaml
  examples/gateway-provisioner/01-roles.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/controller/tcproute.go
  internal/dag/accessors.go
  internal/dag/builder.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/dag/dag.go
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
  internal/debug/dot.go
  internal/featuretests/v3/tcproute_test.go
  internal/gatewayapi/listeners.go
  internal/gatewayapi/listeners_test.go
  internal/k8s/helpers.go
  internal/k8s/helpers_test.go
  internal/k8s/kind.go
  internal/k8s/kind_test.go
  internal/k8s/rbac.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/objects/rbac/clusterrole/cluster_role.go
  internal/status/routeconditions.go
  internal/xdscache/v3/listener.go
  test/e2e/framework.go
  test/e2e/gateway/gateway_test.go
  test/e2e/gateway/tcproute_test.go
  test/e2e/gatewayapi_predicates.go
Labels: release-note/minor

#5479 test tooling: Bump kind and kubectl
  .github/workflows/prbuild.yaml
  hack/actions/install-kubernetes-toolchain.sh
  test/scripts/make-kind-cluster.sh
Labels: release-note/none-required

#5486 internal/dag: Listener processor uses HTTP/S addresses for Gateway Listeners
  internal/dag/builder_test.go
  internal/dag/listener_processor.go
  internal/featuretests/v3/listeners_test.go
Labels: release-note/none-required

#5487 test/e2e/ingress: Use ingress class name spec field
  test/e2e/ingress/ingress_class_test.go
Labels: release-note/none-required

#5489 More test logger fixes
  internal/k8s/statusaddress_test.go
  internal/xds/v3/contour_test.go
  internal/xdscache/v3/server_test.go
Labels: release-note/none-required

#5459 Replace docker/distribution usage with novln/docker-parser
  cmd/contour/gatewayprovisioner.go
  go.mod
  go.sum
  internal/provisioner/parse/parse.go
  internal/provisioner/parse/parse_test.go
Labels: release-note/none-required

#5484 Remove dots in certgen job name
  changelogs/unreleased/5484-tsaarni-small.md
  hack/release/make-release-tag.sh
Labels: release-note/small

#5494 fix wrong typo in Makefile :run-gateway-conformance and lint-flags
  Makefile
Labels: release-note/none-required

#5502 Bump go to 1.20.5
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/5502-sunjayBhatia-small.md
Labels: release-note/small

#5503 release-1.25: Bump go to 1.20.5
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/CHANGELOG-v1.20.0.md
  site/content/posts/2020-01-16-announcing-contour-1.1.md
Labels: release-note/none-required

#5490 docs for install envoy containers.
  site/content/getting-started/_index.md
Labels: release-note/none-required

#5485 services referenced by a GRPCRoute dont trigger a DAG rebuild
  changelogs/unreleased/5485-yanggangtony-small.md
  internal/dag/cache.go
  internal/dag/cache_test.go
Labels: release-note/small

#5492 Fix configmap word in docs.
  site/content/docs/1.23/guides/gateway-api.md
  site/content/docs/1.23/guides/global-rate-limiting.md
  site/content/docs/1.24/guides/gateway-api.md
  site/content/docs/1.24/guides/global-rate-limiting.md
  site/content/docs/1.25/guides/gateway-api.md
  site/content/docs/1.25/guides/global-rate-limiting.md
  site/content/docs/main/guides/gateway-api.md
  site/content/docs/main/guides/global-rate-limiting.md
  site/content/guides/gateway-api.md
  site/content/guides/global-rate-limiting.md
Labels: release-note/none-required

#5508 release-1.24: Bump go to 1.19.10
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/CHANGELOG-v1.20.0.md
  site/content/posts/2020-01-16-announcing-contour-1.1.md
Labels: release-note/none-required

#5514 internal/k8s: Make log test flush timeout more lenient
  internal/k8s/log_test.go
Labels: release-note/none-required

#5512 Skip Gateway API install in upgrade tests
  .github/workflows/prbuild.yaml
  test/scripts/make-kind-cluster.sh
Labels: release-note/none-required

#5415 site: Update guide on building Envoy in FIPS compliant mode
  changelogs/unreleased/5415-sunjayBhatia-docs.md
  site/content/docs/1.25/guides/fips.md
  site/content/docs/main/guides/fips.md
Labels: release-note/docs

#5517 Delete redundance code.
  cmd/contour/servecontext.go
Labels: release-note/none-required

#5518 update pr template notes.
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: release-note/none-required

#5515 test/e2e: add test for Gateway with many Listeners
  test/e2e/gatewayapi_predicates.go
  test/e2e/provisioner/provisioner_test.go
Labels: release-note/none-required

#5521 docs:Delete the link of operator.md
  site/data/docs/main-toc.yml
Labels: release-note/none-required

#5516 Enable HTTPProxy Fractional Mirroring
  apis/projectcontour/v1/httpproxy.go
  changelogs/unreleased/5516-hshamji-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/mirrorpolicy_test.go
  internal/xdscache/v3/route_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/request-routing.md
Labels: release-note/small

#5493 Allow changing per_connection_buffer_limit_bytes using contour configuration for clusters
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/5493-rajatvig-minor.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/envoy/v3/cluster.go
  internal/envoy/v3/cluster_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
Labels: release-note/minor

#5524 enable websockets for Gateway listeners
  changelogs/unreleased/5524-skriss-small.md
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/listener_processor.go
  internal/envoy/v3/listener.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/listeners_test.go
  internal/xdscache/v3/listener.go
  site/content/docs/main/config/websockets.md
Labels: release-note/small

#5528 HTTPProxy: support health check status ranges
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  changelogs/unreleased/5528-skriss-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/dag/policy.go
  internal/envoy/v3/healthcheck.go
  internal/featuretests/v3/cluster_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/featuretests.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/health-checks.md
Labels: release-note/small

#5531 internal/envoy/v3: simplify Route code
  internal/envoy/v3/route.go
Labels: kind/cleanup, release-note/none-required

#5529 Clarify TLS certificate delegation
  apis/projectcontour/v1/httpproxy.go
  changelogs/unreleased/5529-tsaarni-small.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/cache.go
  internal/dag/extension_processor.go
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/dag/status_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small
