Repository projectcontour/contour, pull requests merged in 2023-03, with the labels that each got.

#5130 internal/dag: Allow REQ operator to use HTTP/2 pseudo-headers in headers policy
  changelogs/unreleased/5130-sunjayBhatia-small.md
  internal/dag/policy.go
  internal/dag/policy_test.go
Labels: release-note/small

#5125 Gateway API: clean up conditions and filter processing
  changelogs/unreleased/5125-skriss-small.md
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
  internal/status/routeconditions.go
Labels: release-note/small

#5132 Use constants 'http.MethodGet' instead of string 'GET'
  test/e2e/bench/bench_test.go
  test/e2e/http.go
Labels: release-note/none-required

#5133 remove informer for ContourConfiguration
  cmd/contour/serve.go
  internal/dag/cache.go
  internal/k8s/kind.go
  internal/k8s/kind_test.go
Labels: release-note/none-required

#5134 internal/dag: simplify ut for dag/status
  internal/dag/status_test.go
Labels: release-note/none-required

#5080 cmd/contour: optional CRDs
  changelogs/unreleased/5080-nsimons-minor.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  site/content/docs/main/configuration.md
  site/content/docs/main/deploy-options.md
Labels: release-note/minor

#5109 add gauge metric for DAG cache items
  changelogs/unreleased/5109-izturn-small.md
  cmd/contour/serve.go
  internal/dag/cache.go
  internal/k8s/kind.go
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  site/content/docs/main/guides/metrics/table.md
Labels: release-note/small

#5135 internal/dag: simplify add invalid listener condition for gateway-api
  internal/dag/gatewayapi_processor.go
Labels: release-note/none-required

#5136 internal/dag: remove unneeded route labels in status_test.go
  internal/dag/status_test.go
Labels: release-note/none-required

#5151 Update team.html
  changelogs/unreleased/5151-pnbrown-docs.md
  site/themes/contour/layouts/partials/team.html
Labels: release-note/docs

#5154 fix spelling errors
  design/cors-configuration.md
  site/content/docs/main/config/rate-limiting.md
  site/content/docs/v1.13.0/config/rate-limiting.md
  site/content/docs/v1.13.1/config/rate-limiting.md
  site/content/docs/v1.14.0/config/rate-limiting.md
  site/content/docs/v1.14.1/config/rate-limiting.md
  site/content/docs/v1.14.2/config/rate-limiting.md
  site/content/docs/v1.15.0/config/rate-limiting.md
  site/content/docs/v1.15.1/config/rate-limiting.md
  site/content/docs/v1.15.2/config/rate-limiting.md
  site/content/docs/v1.16.0/config/rate-limiting.md
  site/content/docs/v1.16.1/config/rate-limiting.md
  site/content/docs/v1.17.0/config/rate-limiting.md
  site/content/docs/v1.17.1/config/rate-limiting.md
  site/content/docs/v1.17.2/config/rate-limiting.md
  site/content/docs/v1.18.0/config/rate-limiting.md
  site/content/docs/v1.18.1/config/rate-limiting.md
  site/content/docs/v1.18.2/config/rate-limiting.md
  site/content/docs/v1.18.3/config/rate-limiting.md
  site/content/docs/v1.19.0/config/rate-limiting.md
  site/content/docs/v1.19.1/config/rate-limiting.md
  site/content/docs/v1.20.0/config/rate-limiting.md
  site/content/docs/v1.20.1/config/rate-limiting.md
  site/content/docs/v1.20.2/config/rate-limiting.md
  site/content/docs/v1.21.0/config/rate-limiting.md
  site/content/docs/v1.21.1/config/rate-limiting.md
  site/content/docs/v1.21.2/config/rate-limiting.md
  site/content/docs/v1.21.3/config/rate-limiting.md
  site/content/docs/v1.22.0/config/rate-limiting.md
  site/content/docs/v1.22.1/config/rate-limiting.md
  site/content/docs/v1.22.2/config/rate-limiting.md
  site/content/docs/v1.22.3/config/rate-limiting.md
  site/content/docs/v1.22.4/config/rate-limiting.md
  site/content/docs/v1.23.0/config/rate-limiting.md
  site/content/docs/v1.23.1/config/rate-limiting.md
  site/content/docs/v1.23.2/config/rate-limiting.md
  site/content/docs/v1.23.3/config/rate-limiting.md
  site/content/docs/v1.24.0/config/rate-limiting.md
  site/content/docs/v1.24.1/config/rate-limiting.md
Labels: release-note/none-required

#5064 Avoid comparing full objects during update to optimize performance
  changelogs/unreleased/5064-tsaarni-small.md
  internal/contour/handler.go
  internal/k8s/helpers.go
  internal/k8s/helpers_test.go
  internal/k8s/testdata/endpoint-content-change.yaml
  internal/k8s/testdata/httpproxy-annotation-change.yaml
  internal/k8s/testdata/ingress-annotation-change.yaml
  internal/k8s/testdata/namespace-label-change.yaml
  internal/k8s/testdata/secret-content-change.yaml
  internal/k8s/testdata/secret-metadata-change.yaml
  internal/k8s/testdata/service-annotation-change.yaml
  internal/k8s/testdata/service-status-change.yaml
Labels: release-note/small

#5152 internal/dag: simplify api for gateway-api
  internal/dag/policy.go
Labels: release-note/none-required

#5168 [release-1.22] CI fixes
  .github/workflows/prbuild.yaml
  design/cors-configuration.md
  site/content/docs/main/config/rate-limiting.md
  site/content/docs/v1.13.0/config/rate-limiting.md
  site/content/docs/v1.13.1/config/rate-limiting.md
  site/content/docs/v1.14.0/config/rate-limiting.md
  site/content/docs/v1.14.1/config/rate-limiting.md
  site/content/docs/v1.14.2/config/rate-limiting.md
  site/content/docs/v1.15.0/config/rate-limiting.md
  site/content/docs/v1.15.1/config/rate-limiting.md
  site/content/docs/v1.15.2/config/rate-limiting.md
  site/content/docs/v1.16.0/config/rate-limiting.md
  site/content/docs/v1.16.1/config/rate-limiting.md
  site/content/docs/v1.17.0/config/rate-limiting.md
  site/content/docs/v1.17.1/config/rate-limiting.md
  site/content/docs/v1.17.2/config/rate-limiting.md
  site/content/docs/v1.18.0/config/rate-limiting.md
  site/content/docs/v1.18.1/config/rate-limiting.md
  site/content/docs/v1.18.2/config/rate-limiting.md
  site/content/docs/v1.18.3/config/rate-limiting.md
  site/content/docs/v1.19.0/config/rate-limiting.md
  site/content/docs/v1.19.1/config/rate-limiting.md
  site/content/docs/v1.20.0/config/rate-limiting.md
  site/content/docs/v1.20.1/config/rate-limiting.md
  site/content/docs/v1.20.2/config/rate-limiting.md
  site/content/docs/v1.21.0/config/rate-limiting.md
  site/content/docs/v1.21.1/config/rate-limiting.md
  site/content/docs/v1.22.0/config/rate-limiting.md
Labels: release-note/none-required

#5175 Gateway API: k8s.gcr.io -> registry.k8s.io
  Makefile
  examples/gateway/02-certificate_config.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  hack/generate-gateway-yaml.sh
Labels: release-note/none-required

#5179 [release-1.22] Gateway API: k8s.gcr.io -> registry.k8s.io
  Makefile
  examples/gateway/02-certificate_config.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  hack/generate-gateway-yaml.sh
Labels: release-note/none-required

#5181 [release-1.22] dependency bumps
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
Labels: release-note/none-required

#5183 Fix Gateway API conformance invocation
  test/scripts/run-gateway-conformance.sh
Labels: release-note/none-required

#5185 [release-1.22] update Envoy version in Deployment manifest
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
Labels: release-note/none-required

#5186 docs for v1.24.2, v1.23.4, v1.22.5
  changelogs/CHANGELOG-v1.22.5.md
  changelogs/CHANGELOG-v1.23.4.md
  changelogs/CHANGELOG-v1.24.2.md
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/none-required

#5188 trivy-scan: rename security-checks to scanners
  .github/workflows/trivy-scan.yaml
Labels: release-note/none-required

#5191 update Envoy and golang.org/x/image
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/none-required

#5187 update release process docs and redirects
  netlify.toml
  site/content/resources/release-process.md
Labels: release-note/none-required

#5108 add install-provisioner-working
  Makefile
  test/scripts/install-provisioner-working.sh
Labels: release-note/none-required

#4994 feat: Add HTTP support for External Auth
  apis/projectcontour/v1/helpers.go
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/4994-clayton-gonsalves-minor.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/global-external-auth/01-authserver.yaml
  examples/global-external-auth/02-globalextauth-extsvc.yaml
  examples/global-external-auth/03-contour-config.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/dag/httpproxy_processor_test.go
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/route.go
  internal/featuretests/v3/global_authorization_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/route.go
  internal/xdscache/v3/route_test.go
  pkg/config/parameters.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/guides/external-authorization.md
  test/e2e/deployment.go
  test/e2e/httpproxy/global_external_auth_test.go
  test/e2e/httpproxy/httpproxy_test.go
Labels: release-note/minor

#5010 Internal redirect implementation
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  changelogs/unreleased/5010-Jean-Daniel-minor.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  internal/featuretests/v3/internalredirectpolicy_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/request-routing.md
  test/e2e/httpproxy/httpproxy_test.go
  test/e2e/httpproxy/internal_redirect_test.go
Labels: release-note/minor

#5199 test/e2e/httpproxy: Remove pointer package usage
  test/e2e/httpproxy/httpproxy_test.go
  test/e2e/httpproxy/internal_redirect_test.go
Labels: release-note/none-required

#5210 test/e2e: clone DefaultTransport and disable keep-alives
  test/e2e/http.go
Labels: release-note/none-required

#5044 multiple Listeners design doc
  design/multiple-listeners-design.md
Labels: kind/design, release-note/none-required

#5212 test/e2e: clone DefaultTransport and disable keep-alives for metrics & admin
  test/e2e/http.go
Labels: release-note/none-required

#5155 internal/dag: finish the TODO for `EnsureService`
  internal/dag/accessors.go
  internal/dag/accessors_test.go
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
Labels: release-note/none-required

#5195 HTTPProxy: support Host header rewrites per-service
  apis/projectcontour/v1/httpproxy.go
  changelogs/unreleased/5195-fangfpeng-small.md
  examples/contour/01-crds.yaml
  examples/example-workload/httpproxy/03-routes/httpproxy-header-rewrite.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/builder_test.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  internal/dag/status_test.go
  internal/envoy/route.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/small

#5128 refactor DAG and DAG consumers to support >2 Listeners
  cmd/contour/serve.go
  cmd/contour/serve_test.go
  internal/contour/metrics_test.go
  internal/dag/accessors.go
  internal/dag/builder.go
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/dag/listener_processor.go
  internal/dag/status_test.go
  internal/debug/dot_test.go
  internal/featuretests/v3/backendclientauth_test.go
  internal/featuretests/v3/externalname_test.go
  internal/featuretests/v3/fallbackcert_test.go
  internal/featuretests/v3/featuretests.go
  internal/featuretests/v3/global_authorization_test.go
  internal/featuretests/v3/globalratelimit_test.go
  internal/featuretests/v3/listeners_test.go
  internal/featuretests/v3/route_test.go
  internal/xdscache/v3/listener.go
  internal/xdscache/v3/listener_test.go
  internal/xdscache/v3/route.go
  internal/xdscache/v3/route_test.go
  internal/xdscache/v3/secret_test.go
Labels: release-note/none-required

#5216 test/e2e: retry gRPC Unauthenticated code
  test/e2e/httpproxy/grpc_test.go
Labels: release-note/none-required

#5211 Automatically set GOMAXPROCS to match the number of CPUs available to the container
  changelogs/unreleased/5211-rajatvig-small.md
  cmd/contour/contour.go
  go.mod
  go.sum
Labels: release-note/small

#5218 Bump golang to 1.20.2
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/5118-skriss-small.md
  changelogs/unreleased/5218-sunjayBhatia-small.md
Labels: release-note/small

#5220 Gateway API: Always set Accepted condition on Gateway Listeners
  changelogs/unreleased/5220-sunjayBhatia-small.md
  internal/dag/gatewayapi_processor.go
  internal/dag/status_test.go
Labels: release-note/small

#5217 internal/envoy/v3: Trim trailing slashes from path separated prefix match
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
Labels: release-note/none-required

#4990 Add ip filter design doc
  design/ip-filtering-design.md
Labels: kind/design, release-note/none-required

#5228 test/scripts: fix upgrade from version
  test/scripts/get-contour-upgrade-from-version.sh
Labels: release-note/none-required

#5231 [release-1.22] test/scripts: fix upgrade from version
  test/scripts/get-contour-upgrade-from-version.sh
Labels: release-note/none-required

#5236 site: add Kubernetes slack inviter link
  site/content/community/_index.html
Labels: release-note/none-required
