Repository projectcontour/contour, pull requests merged in 2023-02, with the labels that each got.

#5041 Fix the upgrade e2e test flakiness
  test/e2e/deployment.go
Labels: release-note/none-required

#5050 Bump golangci-lint to 1.51.1
  .github/workflows/prbuild.yaml
  hack/golangci-lint
Labels: release-note/none-required

#5048 test/e2e: Fix wait for Envoy Deployment update
  test/e2e/deployment.go
Labels: release-note/none-required

#5060 site: generalize upgrading instructions
  site/content/resources/upgrading.md
Labels: release-note/none-required

#5062 Use http constants instead of string
  cmd/contour/shutdownmanager_test.go
  internal/envoy/v3/route.go
Labels: release-note/none-required

#5034 feat: Add AllowPrivateNetwork to support Access-Control-Allow-Private-Network
  apis/projectcontour/v1/httpproxy.go
  changelogs/unreleased/5034-lvyanru8200-small.md
  design/cors-configuration.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/dag.go
  internal/dag/httpproxy_processor.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  internal/featuretests/v3/corspolicy_test.go
  internal/xdscache/v3/route_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/cors.md
Labels: release-note/small

#5058 update Envoy to 1.25.1
  Makefile
  changelogs/unreleased/5058-skriss-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/small

#5056 [release-1.22] v1.22.4 patches
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5057 [release-1.23] v1.23.3 patches
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#5063 Gateway API: Bump to v0.6.1 and run all conformance tests
  changelogs/unreleased/5063-sunjayBhatia-small.md
  examples/gateway/00-crds.yaml
  examples/gateway/01-admission_webhook.yaml
  examples/gateway/02-certificate_config.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  go.mod
  go.sum
  test/conformance/gatewayapi/gateway_conformance_test.go
  test/scripts/run-gateway-conformance.sh
Labels: release-note/small

#4995 Design: ExtAuth HTTP support
  design/global-external-authorization-design.md
Labels: kind/design, release-note/none-required

#5076 internal/sorter: Fix sorting for Query parameter matches
  internal/sorter/sorter.go
  internal/sorter/sorter_test.go
  internal/xdscache/v3/route.go
  internal/xdscache/v3/route_test.go
Labels: release-note/none-required

#5068 Gateway API: support RequestRedirect path rewrite
  changelogs/unreleased/5068-skriss-small.md
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
Labels: release-note/small

#5049 Bump Go to 1.20.0
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/5049-sunjayBhatia-small.md
  internal/featuretests/v3/featuretests.go
Labels: release-note/small

#5087 test/e2e/gateway: Remove more duplicate tests
  test/e2e/gateway/gateway_test.go
  test/e2e/gateway/path_condition_match_test.go
  test/e2e/gateway/tlsroute_test.go
Labels: release-note/none-required

#5095 bump go-control-plane to v0.11.0
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#4957 design: add tracing design doc
  design/tracing-design.md
Labels: kind/design, release-note/none-required

#5094 test: use helper to generate ObjectMeta
  internal/dag/status_test.go
  internal/featuretests/v3/backendcavalidation_test.go
  internal/featuretests/v3/ingressclass_test.go
  internal/featuretests/v3/listeners_test.go
  internal/featuretests/v3/replaceprefix_test.go
  internal/featuretests/v3/retrypolicy_test.go
  internal/featuretests/v3/route_test.go
  internal/featuretests/v3/routeweight_test.go
  internal/featuretests/v3/timeoutpolicy_test.go
  internal/featuretests/v3/tlscertificatedelegation_test.go
  internal/featuretests/v3/tlsprotocolversion_test.go
  internal/featuretests/v3/tlsroute_test.go
  internal/featuretests/v3/websockets_test.go
  internal/fixture/meta.go
Labels: release-note/none-required

#5105 internal/dag: replace custom helpers with ref.Val
  internal/dag/gatewayapi_processor.go
  internal/dag/ingress_processor.go
Labels: release-note/none-required

#5118 update to Go 1.20.1
  .github/workflows/build_daily.yaml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/5118-skriss-small.md
  go.mod
  go.sum
Labels: release-note/small

#5119 hack: change CRD YAML temp dir template
  hack/generate-crd-yaml.sh
Labels: release-note/none-required

#5121 remove version string from mock file headers
  internal/controller/controller_test.go
  internal/controller/mocks/manager.go
  internal/debug/dot_test.go
  internal/debug/mocks/dag_builder.go
  internal/k8s/mocks/cache.go
  internal/k8s/statusaddress_test.go
  internal/leadership/mocks/need_leader_election_notification.go
  internal/leadership/notifier_test.go
Labels: release-note/none-required

#5114 Gateway API: add GRPCRoute support
  changelogs/unreleased/5114-fangfpeng-minor.md
  cmd/contour/serve.go
  examples/contour/02-role-contour.yaml
  examples/gateway-provisioner/01-roles.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/contour/handler.go
  internal/controller/controller_test.go
  internal/controller/grpcroute.go
  internal/dag/builder_test.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/dag/gatewayapi_processor.go
  internal/dag/gatewayapi_processor_test.go
  internal/dag/policy.go
  internal/dag/status_test.go
  internal/gatewayapi/helpers.go
  internal/k8s/kind.go
  internal/k8s/kind_test.go
  internal/k8s/rbac.go
  internal/provisioner/objects/rbac/clusterrole/cluster_role.go
  internal/status/routeconditions.go
Labels: release-note/minor

#5126 Update grpc.md
  site/content/docs/main/guides/grpc.md
Labels: release-note/none-required

#5124 internal/dag: merge common route processing code
  internal/dag/gatewayapi_processor.go
Labels: release-note/none-required

#5129 Upgrade docsearch to v3
  changelogs/unreleased/5129-pnbrown-docs.md
  site/config.yaml
  site/themes/contour/layouts/_default/baseof.html
  site/themes/contour/layouts/_default/search.html
Labels: area/website, release-note/docs
