Repository projectcontour/contour, pull requests merged in 2024-03, with the labels that each got.

#6243 use multi-arch golang base image
  Makefile
Labels: release-note/none-required

#6230 Fix for specifying a health check port with an ExternalName Service
  changelogs/unreleased/6230-yangyy93-small.md
  internal/envoy/v3/cluster_test.go
  internal/envoy/v3/endpoint.go
  internal/envoy/v3/endpoint_test.go
Labels: release-note/small

#6245 Ignore all loopback IPs in local ip grep
  Makefile
Labels: release-note/none-required

#6251 test/e2e/gateway: check service as part of request condition
  test/e2e/gateway/request_header_modifier_test.go
Labels: release-note/none-required

#6250 use a separate snapshot cache for EDS
  changelogs/unreleased/6250-skriss-small.md
  cmd/contour/serve.go
  internal/protobuf/helpers.go
  internal/protobuf/helpers_test.go
  internal/xdscache/v3/endpointslicetranslator.go
  internal/xdscache/v3/endpointstranslator.go
  internal/xdscache/v3/snapshot.go
Labels: release-note/small

#6252 test/e2e/gateway: prevent tcproute test causing pollution
  test/e2e/gateway/tcproute_test.go
  test/e2e/http.go
Labels: release-note/none-required

#6265 Bump golang to 1.22.1 for CVEs
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/6181-sunjayBhatia-small.md
  changelogs/unreleased/6265-sunjayBhatia-small.md
Labels: release-note/small

#6255 use envoy xDS server for featuretests
  internal/featuretests/v3/cluster_test.go
  internal/featuretests/v3/endpoints_test.go
  internal/featuretests/v3/featuretests.go
  internal/featuretests/v3/secrets_test.go
  internal/xdscache/v3/snapshot.go
Labels: release-note/none-required

#6146 change default xDS server to envoy
  .github/workflows/build_daily.yaml
  apis/projectcontour/v1alpha1/contourconfig.go
  changelogs/unreleased/6146-skriss-deprecation.md
  changelogs/unreleased/6146-skriss-major.md
  cmd/contour/servecontext_test.go
  examples/contour/01-contour-config.yaml
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/contourconfig/contourconfiguration.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
  test/e2e/fixtures.go
Labels: release-note/major, release-note/deprecation

#6289 release-1.28: Bump Envoy to v1.29.2
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#6283 Bump Envoy to v1.29.2
  Makefile
  changelogs/unreleased/6283-sunjayBhatia-minor.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/minor

#6288 Disable Envoy removing TE request header
  .codespell.ignorewords
  changelogs/unreleased/6288-sunjayBhatia-minor.md
  internal/envoy/v3/runtime.go
  internal/envoy/v3/runtime_test.go
  internal/xdscache/v3/runtime_test.go
Labels: release-note/minor

#6290 release-1.28: Disable Envoy removing TE request header
  .codespell.ignorewords
  internal/envoy/v3/runtime.go
  internal/envoy/v3/runtime_test.go
  internal/xdscache/v3/runtime_test.go
Labels: release-note/none-required

#6292 1.28.2 release note and docs
  changelogs/CHANGELOG-v1.28.2.md
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/none-required

#6298 chore: fix some comments
  site/content/docs/1.20/configuration.md
  site/content/docs/1.21/configuration.md
  site/content/docs/1.22/configuration.md
  site/content/docs/1.23/configuration.md
  site/content/docs/1.24/configuration.md
  site/content/docs/1.25/configuration.md
  site/content/docs/1.26/configuration.md
  site/content/docs/1.27/configuration.md
  site/content/docs/1.28/configuration.md
  site/content/docs/main/configuration.md
  site/content/docs/v1.14.0/configuration.md
  site/content/docs/v1.14.1/configuration.md
  site/content/docs/v1.14.2/configuration.md
  site/content/docs/v1.15.0/configuration.md
  site/content/docs/v1.15.1/configuration.md
  site/content/docs/v1.15.2/configuration.md
  site/content/docs/v1.16.0/configuration.md
  site/content/docs/v1.16.1/configuration.md
  site/content/docs/v1.17.0/configuration.md
  site/content/docs/v1.17.1/configuration.md
  site/content/docs/v1.17.2/configuration.md
  site/content/docs/v1.18.0/configuration.md
  site/content/docs/v1.18.1/configuration.md
  site/content/docs/v1.18.2/configuration.md
  site/content/docs/v1.18.3/configuration.md
  site/content/docs/v1.19.0/configuration.md
  site/content/docs/v1.19.1/configuration.md
Labels: release-note/none-required

#6293 Bugfender is using contour
  site/content/resources/adopters.md
  site/themes/contour/static/img/adopters/bugfender.svg
Labels: release-note/none-required
