Repository projectcontour/contour, pull requests merged in 2024-01, with the labels that each got.

#6013 Adds support for global circuit budget
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/6013-davinci26-minor.md
  cmd/contour/serve.go
  cmd/contour/serve_test.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/gatewayapi_processor.go
  internal/dag/httpproxy_processor.go
  internal/dag/ingress_processor.go
  internal/dag/policy.go
  internal/dag/policy_test.go
  internal/featuretests/v3/cluster_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
Labels: release-note/minor

#5927 clarify logic in endpointstranslator.go
  internal/xdscache/v3/endpointslicetranslator.go
  internal/xdscache/v3/endpointstranslator.go
Labels: release-note/none-required

#6048 Add action for generating OpenSSF scorecard
  .github/workflows/openssf-scorecard.yaml
Labels: release-note/none-required

#6051 Use exact version number for ossf/scorecard-action
  .github/workflows/openssf-scorecard.yaml
Labels: release-note/none-required

#6053 Bump go to 1.21.5
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/6053-sunjayBhatia-small.md
Labels: release-note/small

#6052 Pin github actions using shas
  .github/workflows/build_daily.yaml
  .github/workflows/build_main.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/label_check.yaml
  .github/workflows/openssf-scorecard.yaml
  .github/workflows/prbuild.yaml
  .github/workflows/request-reviews.yaml
  .github/workflows/stale.yaml
  .github/workflows/trivy-scan.yaml
Labels: release-note/none-required

#6016 internal/dag: Add support for per-host max connections
  changelogs/unreleased/6016-relu-small.md
  internal/annotation/annotations.go
  internal/dag/accessors.go
  internal/dag/builder_test.go
  internal/dag/dag.go
  internal/envoy/v3/cluster.go
  internal/envoy/v3/cluster_test.go
  internal/featuretests/v3/cluster_test.go
  internal/xdscache/v3/cluster_test.go
  site/content/docs/main/config/annotations.md
Labels: release-note/small

#6057 internal/featuretests: fix test merge conflicts
  internal/featuretests/v3/cluster_test.go
Labels: release-note/none-required

#5849 allow multiple SANS in upstream validation
  apis/projectcontour/v1/httpproxy.go
  apis/projectcontour/v1/zz_generated.deepcopy.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/5849-KauzClay-deprecation.md
  changelogs/unreleased/5849-KauzClay-minor.md
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/dag/builder_test.go
  internal/dag/cache.go
  internal/dag/cache_test.go
  internal/dag/dag.go
  internal/dag/dag_test.go
  internal/dag/extension_processor.go
  internal/envoy/cluster.go
  internal/envoy/v3/auth.go
  internal/envoy/v3/auth_test.go
  internal/envoy/v3/cluster_test.go
  internal/envoy/v3/listener_test.go
  internal/featuretests/v3/backendclientauth_test.go
  internal/featuretests/v3/envoy.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/upstream-tls.md
  test/e2e/httpproxy/cel_validation_test.go
  test/e2e/httpproxy/httpproxy_test.go
Labels: release-note/minor, release-note/deprecation

#6056 chore: add snappcloud to adopters
  site/content/resources/adopters.md
  site/themes/contour/static/img/adopters/snappcloud.png
Labels: release-note/none-required

#6062 Internal: replace funcs with the builtin
  internal/envoy/cluster.go
  internal/xdscache/v3/listener.go
Labels: release-note/none-required

#6061 Add instructions for docker-mac-net-connect and installation instructions to contributing guide
  CONTRIBUTING.md
Labels: release-note/none-required

#6058 feat: add max-connections-per-listener config option
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/6058-flawedmatrix-minor.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/xdscache/v3/runtime.go
  internal/xdscache/v3/runtime_test.go
  pkg/config/parameters.go
  pkg/config/parameters_test.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/minor

#6063 Remove static base runtime layer from bootstrap
  changelogs/unreleased/6063-lubronzhan-small.md
  internal/envoy/v3/bootstrap.go
  internal/envoy/v3/bootstrap_test.go
Labels: release-note/small

#6069 Improve e2e helper updateAndWaitFor to avoid conflicts
  test/e2e/fixtures.go
  test/e2e/framework.go
Labels: release-note/none-required

#6068 Use minimum permissions for github token in PR workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/label_check.yaml
  .github/workflows/prbuild.yaml
  .github/workflows/request-reviews.yaml
  .github/workflows/welcome-new-contributors.yaml
Labels: release-note/none-required

#6072 Update minimum permissions on remaining workflows
  .github/workflows/build_daily.yaml
  .github/workflows/build_main.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/openssf-scorecard.yaml
  .github/workflows/stale.yaml
  .github/workflows/trivy-scan.yaml
Labels: release-note/none-required

#6074 Add OpenSSF scorecard to README
  README.md
Labels: release-note/none-required

#6091 Enable testifylint and ginkgo linters
  .golangci.yml
  apis/projectcontour/v1alpha1/accesslog_test.go
  cmd/contour/certgen_test.go
  internal/annotation/annotations_test.go
  internal/contourconfig/contourconfiguration_test.go
  internal/dag/accessors_test.go
  internal/dag/cache_test.go
  internal/dag/conditions_test.go
  internal/dag/dag_test.go
  internal/dag/policy_test.go
  internal/envoy/cluster_test.go
  internal/envoy/v3/bootstrap_test.go
  internal/envoy/v3/cluster_test.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/socket_options_test.go
  internal/gatewayapi/listeners_test.go
  internal/httpsvc/http_test.go
  internal/k8s/helpers_test.go
  internal/k8s/log_test.go
  internal/k8s/statusaddress_test.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/provisioner/objects/contourconfig/contourconfig_test.go
  internal/provisioner/objects/object_test.go
  internal/status/cache_test.go
  internal/timeout/timeout_test.go
  internal/timeout/validation_test.go
  internal/xds/v3/callbacks_test.go
  internal/xds/v3/contour_test.go
  pkg/certs/certgen_test.go
  pkg/config/parameters_test.go
  test/e2e/gateway/response_header_modifier_test.go
  test/e2e/httpproxy/cookie_rewrite_test.go
  test/e2e/httpproxy/fqdn_test.go
  test/e2e/httpproxy/grpc_test.go
  test/e2e/httpproxy/internal_redirect_test.go
  test/e2e/httpproxy/namespaces_test.go
  test/e2e/httpproxy/request_redirect_test.go
  test/e2e/upgrade/upgrade_test.go
Labels: release-note/none-required

#6096 Add flag to golangci-lint to show line number if there is error
  .github/workflows/prbuild.yaml
Labels: release-note/none-required

#6097 Update proxy-proto.md to remove warning about aws load balancer annotations not working
  site/content/docs/1.25/guides/proxy-proto.md
  site/content/docs/1.26/guides/proxy-proto.md
  site/content/docs/1.27/guides/proxy-proto.md
  site/content/docs/main/guides/proxy-proto.md
Labels: release-note/none-required

#6099 Remove initial readiness probe delay
  changelogs/unreleased/6099-sunjayBhatia-minor.md
  examples/contour/03-contour.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/provisioner/objects/deployment/deployment.go
Labels: release-note/minor

#6116 Add note to warn people to add config to vscode if need to compile fo…
  CONTRIBUTING.md
Labels: release-note/none-required

#6117 Add more debugging log on generating crd related code.
  hack/actions/check-uncommitted-codegen.sh
  hack/generate-crd-deepcopy.sh
  hack/generate-crd-yaml.sh
  hack/generate-rbac.sh
Labels: release-note/none-required

#6077 feat(access-log): omit empty fields in Envoy logs
  changelogs/unreleased/6077-abbas-gheydi-small.md
  internal/envoy/v3/accesslog.go
  internal/envoy/v3/accesslog_test.go
  site/content/docs/main/config/access-logging.md
Labels: release-note/small

#6118 Bump certyaml to fix race condition
  go.mod
  go.sum
Labels: release-note/none-required

#6124 internal/envoy: use consistent HTTP filter names
  changelogs/unreleased/6124-skriss-small.md
  internal/envoy/v3/listener.go
  internal/envoy/v3/listener_test.go
  internal/envoy/v3/route.go
  internal/envoy/v3/route_test.go
  internal/featuretests/v3/authorization_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/global_authorization_test.go
  internal/featuretests/v3/ipfilter_test.go
  internal/featuretests/v3/jwtverification_test.go
  internal/featuretests/v3/localratelimit_test.go
  internal/xdscache/v3/route_test.go
Labels: release-note/small

#6079 Added support for upstream verification for TCPProxy
  changelogs/unreleased/6079-tsaarni-minor.md
  internal/dag/httpproxy_processor.go
  internal/featuretests/v3/backendcavalidation_test.go
  internal/featuretests/v3/backendclientauth_test.go
Labels: release-note/minor

#6123 bump Envoy to v1.29.0
  Makefile
  changelogs/unreleased/6123-skriss-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/small

#6143 site: document Gateway name length limit
  changelogs/unreleased/6143-skriss-docs.md
  site/content/docs/1.26/config/gateway-api.md
  site/content/docs/1.27/config/gateway-api.md
  site/content/docs/main/config/gateway-api.md
Labels: release-note/docs

#6147 provisioner: Set SupportedVersion condition on GatewayClass
  changelogs/unreleased/6147-sunjayBhatia-small.md
  examples/gateway-provisioner/01-roles.yaml
  examples/render/contour-gateway-provisioner.yaml
  internal/provisioner/controller/gatewayclass.go
  internal/provisioner/controller/gatewayclass_test.go
  internal/provisioner/rbac/rbac.go
  internal/provisioner/scheme.go
  test/e2e/provisioner/provisioner_test.go
Labels: release-note/small

#6144 deprecate configuring Contour with a Gateway controller name
  apis/projectcontour/v1alpha1/contourconfig.go
  changelogs/unreleased/6144-skriss-deprecation.md
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  pkg/config/parameters.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/config/gateway-api.md
  site/content/docs/main/configuration.md
  site/content/guides/gateway-api.md
  test/e2e/gateway/gateway_test.go
Labels: kind/deprecation, release-note/deprecation
