Repository projectcontour/contour, pull requests merged in 2024-06, with the labels that each got.

#6484 release-1.29: Bump Envoy to 1.30.2
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#6485 release-1.28: Bump Envoy to 1.29.5
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#6483 Bump Envoy to 1.30.2
  Makefile
  changelogs/unreleased/6483-sunjayBhatia-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/small

#6486 release-1.27: Bump Envoy to 1.28.4
  .codespell.ignorewords
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#6499 Bump golang to 1.22.4
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/6499-sunjayBhatia-small.md
Labels: release-note/small

#6500 release-1.29: Bump golang to 1.22.4
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
Labels: release-note/none-required

#6501 release-1.28: Bump golang to 1.21.11
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
Labels: release-note/none-required

#6502 release-1.27: Bump golang to 1.21.11
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/prbuild.yaml
  Makefile
Labels: release-note/none-required

#6503 Enable admin route for `stats/prometheus`
  changelogs/unreleased/6503-clayton-gonsalves-small.md
  internal/envoy/v3/stats.go
  internal/envoy/v3/stats_test.go
Labels: kind/bug, release-note/small

#6508 1.27.4, 1.28.5, 1.29.1 release notes and docs updates
  changelogs/CHANGELOG-v1.27.4.md
  changelogs/CHANGELOG-v1.28.5.md
  changelogs/CHANGELOG-v1.29.1.md
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/none-required

#6523 shutdown manager: use filter on downstream_cx_active stats url
  changelogs/unreleased/6523-therealak12-small.md
  cmd/contour/shutdownmanager.go
Labels: release-note/small
