Repository projectcontour/contour, pull requests merged in 2024-08, with the labels that each got.

#6594 chang the envoy version to v1.31.0
  Makefile
Labels: release-note/none-required

#6595 remove unused Makefile variables
  Makefile
Labels: release-note/none-required

#6586 Clarified how XFCC headers are handled
  site/content/docs/main/config/tls-termination.md
Labels: release-note/none-required

#6585 Update README.md to be more helpful
  docs/README.md
Labels: lifecycle/stale, release-note/none-required

#6616 [api-gateway]: Support http(s) as AppProtocol in Kubernetes svc
  changelogs/unreleased/6616-Krast76-small.md
  internal/dag/accessors.go
  internal/dag/accessors_test.go
Labels: release-note/small

#6642 Bump kind 0.24.0 and kubectl 1.31.0
  hack/actions/install-kubernetes-toolchain.sh
Labels: area/dependency, area/tooling, release-note/none-required
