Repository projectcontour/contour, pull requests merged in 2025-05, with the labels that each got.

#6794 Bootstrap flag for connection limit overload manager resource monitor
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/contourconfig_helpers.go
  apis/projectcontour/v1alpha1/contourdeployment.go
  apis/projectcontour/v1alpha1/zz_generated.deepcopy.go
  changelogs/unreleased/6794-seth-epps-minor.md
  cmd/contour/bootstrap.go
  cmd/contour/contour.go
  cmd/contour/serve.go
  cmd/contour/servecontext.go
  cmd/contour/servecontext_test.go
  examples/contour/01-contour-config.yaml
  examples/contour/01-crds.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/envoy/bootstrap.go
  internal/envoy/bootstrap_test.go
  internal/envoy/v3/bootstrap.go
  internal/envoy/v3/bootstrap_test.go
  internal/envoy/v3/stats.go
  internal/envoy/v3/stats_test.go
  internal/featuretests/v3/envoy.go
  internal/featuretests/v3/featuretests.go
  internal/featuretests/v3/listeners_test.go
  internal/provisioner/controller/gateway.go
  internal/provisioner/controller/gateway_test.go
  internal/provisioner/model/model.go
  internal/provisioner/objects/dataplane/dataplane.go
  internal/provisioner/objects/dataplane/dataplane_test.go
  internal/xdscache/v3/listener.go
  pkg/config/parameters.go
  site/content/docs/main/config/api-reference.html
  site/content/docs/main/configuration.md
  test/e2e/bootstrap/bootstrap_test.go
  test/e2e/deployment.go
Labels: release-note/minor

#7019 Bump golang to 1.24.2
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/6918-tsaarni-small.md
  changelogs/unreleased/7019-sunjayBhatia-small.md
Labels: release-note/small

#7008 Remove EndpointsTranslator and feature flag
  apis/projectcontour/v1alpha1/contourconfig.go
  apis/projectcontour/v1alpha1/contourconfig_helpers.go
  apis/projectcontour/v1alpha1/contourconfig_helpers_test.go
  changelogs/unreleased/7008-sunjayBhatia-deprecation.md
  cmd/contour/serve.go
  examples/contour/01-crds.yaml
  examples/contour/02-role-contour.yaml
  examples/gateway-provisioner/01-roles.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway-provisioner.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  internal/featuretests/kubernetes.go
  internal/featuretests/v3/authorization_test.go
  internal/featuretests/v3/endpoints_test.go
  internal/featuretests/v3/extensionservice_test.go
  internal/featuretests/v3/featuretests.go
  internal/featuretests/v3/global_authorization_test.go
  internal/featuretests/v3/listeners_test.go
  internal/featuretests/v3/tracing_test.go
  internal/featuretests/v3/upstreamtls_test.go
  internal/k8s/helpers.go
  internal/k8s/helpers_test.go
  internal/k8s/kind.go
  internal/k8s/kind_test.go
  internal/k8s/rbac.go
  internal/k8s/testdata/endpoint-content-change.yaml
  internal/provisioner/objects/rbac/util/util.go
  internal/xdscache/v3/contour_test.go
  internal/xdscache/v3/endpointslicetranslator.go
  internal/xdscache/v3/endpointslicetranslator_test.go
  internal/xdscache/v3/endpointstranslator.go
  internal/xdscache/v3/endpointstranslator_test.go
  internal/xdscache/v3/snapshot.go
  pkg/config/parameters.go
  site/content/docs/main/config/api-reference.html
Labels: release-note/deprecation

#6872 Prevent LoadBalancer updates on follower.
  changelogs/unreleased/6872-tsaarni-small.md
  cmd/contour/ingressstatus.go
  cmd/contour/serve.go
Labels: release-note/small

#7031 Retry until envoy client cert is rotated
  test/e2e/httpproxy/backend_tls_test.go
Labels: release-note/none-required

#7028 Fix gateway api conformance report generation
  test/conformance/gatewayapi/gateway_conformance_test.go
Labels: release-note/none-required

#7032 Remove daily build endpoints-specific e2e test
  .github/workflows/build_daily.yaml
  test/e2e/fixtures.go
  test/e2e/infra/infra_test.go
Labels: kind/cleanup, release-note/none-required

#7033 Bump Envoy to 1.34.1
  changelogs/unreleased/7033-tsaarni-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/small

#7042 Remove reviewers from dependabot config
  .github/dependabot.yml
Labels: area/tooling, release-note/none-required

#7043 release-1.30: Bump golang.org/x/net to 0.38.0
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#7046 release-1.31: Bump Envoy to 1.34.1
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#7045 release-1.30: Bump envoy to 1.31.8
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: release-note/none-required

#6906 Use LinearCache to optimize StreamEndpoint discovery.
  changelogs/unreleased/6906-tsaarni-small.md
  internal/xdscache/v3/endpointslicetranslator.go
  internal/xdscache/v3/snapshot.go
Labels: release-note/small

#7049 release-1.30: Bump go to 1.24.3
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
  go.mod
Labels: area/dependency, release-note/none-required

#7050 release-1.31: Bump go to 1.24.3
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
Labels: area/dependency, release-note/none-required

#7051 Bump go to 1.24.3
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/7051-sunjayBhatia-small.md
Labels: area/dependency, release-note/small

#7053 Protect endpointslicetranslator.entries on change
  internal/xdscache/v3/endpointslicetranslator.go
Labels: release-note/none-required
