Repository projectcontour/contour, pull requests merged in 2025-01, with the labels that each got.

#6835 release-1.30: Bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#6836 release-1.29: Bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#6837 release-1.28: Bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: area/dependency, release-note/none-required

#6838 Bump go to 1.23.4
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
  changelogs/unreleased/6718-tsaarni-small.md
  changelogs/unreleased/6838-sunjayBhatia-small.md
Labels: area/dependency, release-note/small

#6839 release-1.30: Bump go to 1.22.10
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
Labels: area/dependency, release-note/none-required

#6840 release-1.29: Bump go to 1.22.10
  .github/workflows/build_daily.yaml
  .github/workflows/build_tag.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prbuild.yaml
  Makefile
Labels: area/dependency, release-note/none-required

#6841 Bump envoy to 1.32.3 and use go-control-plane/envoy versioned module for APIs
  changelogs/unreleased/6714-tsaarni-small.md
  changelogs/unreleased/6841-sunjayBhatia-small.md
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
  go.mod
  go.sum
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: area/dependency, release-note/small

#6842 release-1.30: Bump Envoy to 1.31.5
  Makefile
  cmd/contour/gatewayprovisioner.go
  examples/contour/03-envoy.yaml
  examples/deployment/03-envoy-deployment.yaml
  examples/render/contour-deployment.yaml
  examples/render/contour-gateway.yaml
  examples/render/contour.yaml
Labels: area/dependency, release-note/none-required

#6845 Patch release docs/changelogs for 1.30.2, 1.29.4, 1.28.8
  changelogs/CHANGELOG-v1.28.8.md
  changelogs/CHANGELOG-v1.29.4.md
  changelogs/CHANGELOG-v1.30.2.md
  site/content/resources/compatibility-matrix.md
  versions.yaml
Labels: release-note/none-required

#6884 Fix codespell error to pass CI
  design/external-authorization-design.md
Labels: release-note/none-required

#6885 Remove workaround for gen-crd-api-reference-docs
  go.mod
  go.sum
  hack/generate-api-docs.sh
  site/content/docs/main/config/api-reference.html
Labels: release-note/none-required
